{function="load_lang('ui/index')"}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>{$title}</title>
    <link rel="shortcut icon" href="{function="add_style('favicon.ico', ASSETS_DIR)"}" />
    <link rel="stylesheet" type="text/css" href="{function="add_style('main_ar.css', ASSETS_DIR.'/indx/css/')"}" />
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta http-equiv="imagetoolbar" content="no" />
    <script src="{function="add_style('mt-core.js', ASSETS_DIR.'/indx/js/')"}" type="text/javascript"></script>
    <script src="{function="add_style('new.js', ASSETS_DIR.'/indx/js/')"}" type="text/javascript"></script>
    <script src="{function="add_style('new2.js', ASSETS_DIR.'/indx/js/')"}" type="text/javascript"></script>
    <style type="text/css">
    	li.c4 {background-image:url('{function="add_style('en2_big.jpg', ASSETS_DIR.'/indx/images/welten/')"}');}
    	li.c3 {background-image:url('{function="add_style('en1_big_g.jpg', ASSETS_DIR.'/indx/images/welten/')"}');}
    	div.c2 {left:237px;}
    	ul.c1 {position:absolute; left:0px; width: 686px;}
    </style>
</head>

<body class="webkit contentPage">
	<div class="wrapper">
        <div id="country_select">
        </div>
		<div id="header">
			<h1> {#WELCOME} </h1>
		</div>
		<div id="navigation">
			<a href="index" class="home"><img src="{function="add_style('x.gif', ASSETS_DIR)"}" alt=""/></a>
			<table class="menu">
				<tr>
                	<td><a href="manual"><span>  </span></a></td>
                    <td><a href="training"><span>  </span></a></td>
                    <td><a href=" {#FORUM_LINK} " target="_blank"><span>  </span></a></td>
                    <td><a href="register"><span> {#REGISTER} </span></a></td>
                    <td><a href="login"><span> {#LOGIN} </span></a></td>
				</tr>
			</table>
		</div>
		<div id="content">
			<div class="grit">
                {$content}
            </div>
        </div>
        <div id="footer">
        			<div class="container">
        				<ul class="menu">
        					<li><a href="manual"> </a>|</li>
                            <li><a href=" {#FORUM_LINK} "> </a>|</li>
                            <li><a href="login"> </a>|</li>
                            <li><a href="index"> </a>|</li>
                            <li class="copyright">&copy; جميع الحقوق محفوظة لاستضافة الامل</li>
                       </ul>
        			</div>
        </div>
    </div>
</body>
</html>
