<?php
define("BIGHEAD", "Privacy policy");
define("MIDDLEHEAD_1", "An Introduction");
define("TEXT_1", "This document is the Privacy Policy Techno Games Online, based (13 Saad Bin Abi Waqas St., El Haram, Giza, Egypt) (. This policy applies to all websites and mobile apps and games that are Managed by a company Techno Games Online) And if there is a link to a website that is already managed Techno Games Online It guides you to website that is not previously managed Techno Games Online, Or if you access other party services) such as when Make payment (will not apply Privacy Policy. Techno Games Online Those on the website The other party. rise Techno Games Online Any processing, storage or storage of any data you voluntarily submit to Techno Games Online   Such as regular models or other sites and games that are managed by Techno Games Online By means Electronic or any other means of communication, or that is being hacked during the act between you and websites and special games Company Techno Games Online, And according to the following sections and in line with the prevailing regulations. This includes the data you provide to other users when communicating with them on and through the Web Games that are managed by Techno Games Online.");
define("MIDDLEHEAD_2", "1. Visit the websites of the company Techno Games Online");
define("TEXT_2", "IP address, Browser version, screen resolution, and the operating system of the device you are using to access the website. Your browser will also provide data, time and time of your visit to the website and other sites you have accessed through the visit. Used Techno Games Online This information is to improve these websites and games. In addition To that, a company is used Techno Games Online System analysis tool Google Analytics In their positions e. Please read the comments in Article 4 (d For more details about the use of the system Google Analytics.");
define("MIDDLEHEAD_3", "2. Use games Techno Games Online");
define("SMALLHEAD_1", "A - Registration");
define("TEXT_3", "When you register for a game that is already playing Techno Games Online, You will be prompted to enter your email address and choose your username and password. This data will be stored before Techno Games Online When you validate the activation link we send to you via email when you register. If not Check the link, the data will be deleted after two weeks. Please do not use your real name, someone else's name or Trademarks are protected and registered in the user name submission. Moreover, I will set you Techno Games Online Country based address IP For the device you have entered. This information will be saved in order to be able to provide Appropriate selection of payment methods.
<br/>If you click on any ad link on a website Techno Games Online You will be redirected afterwards To a website that is already running Techno Games Online, The cookie that includes the cookie will be set Information about any ad link you clicked on, for any ad, for any game, at any time and in any country. It will also be appointed a company Techno Games Online State you based on the IP address Of your device. I will evaluate Techno Games Online This data is personal to improve Campaigns Ad, as well as the calculation for the purposes of private advertisers have. Cookies will be cleared once the activation link is validated.
<br/>It is Techno Games Online Providing services for increasing numbers of games that allow you to activate only one game at One time use this game account to navigate among many of the games it occupies Techno Games Online Easily He is pleased. This service is basically based on the fact that the data you provide will be stored when you register for the game at a central location By the related game.");
define("SMALLHEAD_2", "B - Use of Games");
define("TEXT_4", "Store Techno Games Online Your personal data is processed to execute the user contract of the game that has been agreed upon, and options Associated with use of this contract), such as the use of games, improved support, etc. (. You will also use the company Techno Games Online Analysis tools Google Analytics For her games. Please read the information in the article 4. (D and e (For more details about the use of the system Google Analytics. The same applies if You reach the games Techno Games Online Using one of the mobile apps run by a company Techno Games Online.");
define("SMALLHEAD_3", "C - channels of communication");
define("TEXT_5", "Techno Games Online Or other players. Used Techno Games Online Automatic filtering systems that prevent any Etisalat violates the terms and conditions of the company Techno Games Online. In particular, used Techno Games Online Automatic filtering systems to block any group e-mail messages or messages that involve insulting, insulting Sexual, or ethnic, and which condones violence or any statements or messages of another function that advertise the products of or Services. Moreover, recording Techno Games Online Use the communication channels for a short period to decompose any Technical errors and fixes, and to ensure the security and integrity of the system and the issuance of user statistics on an impersonal basis. It contains The report issued on the date and time of the message, the sender and the recipient 's name, and the size of the data sent.
No employee will have Techno Games Online Read your messages without your consent. In case you suspect Techno Games Online Misuse and / or use of unauthorized communication channels available), for example, when receiving a report (, the Techno Games Online Reserves the right to check the relevant game account and messages sent from it and to take other action in If necessary .");
define("SMALLHEAD_4", "E - Check the manipulation of the play operations");
define("TEXT_6", "You will Techno Games Online All records are stored and reflect how the websites are used And games that are managed by Techno Games Online, Such as user activities within the game and communication within the game Between users or communicating within the services associated with the game. This includes monitoring of game play and verification of any Potential manipulation of the game, which can later lead to the discovery of any offensive or inappropriate activities Users. Used Techno Games Online Special programs to detect any violations on game rules, such as programs Which can detect the use of any unauthorized texts. To do this, addresses can be stored IP, Data Login for the last 40 days, and other data that the browser portrays as header information. Moreover, she did Techno Games Online Appoint individuals who have received specific training to do so and who may be employees of the company Or self-employed with Techno Games Online. Will choose Techno Games Online Appropriate individuals Of the classified players who voluntarily expressed their interest in carrying out such tasks. Staff will have, Self - employed and volunteers) trainees specially trained individuals (access to the same data, as the programs Special used by Techno Games Online Implement the tasks assigned to them. The trained personnel will be recruited Special training to identify, detect and punish any violation of current general terms and conditions and rules of play, such as non-use Legal for many gaming accounts or directing insult to other players. Specially trained staff work Exclusive in line with the texts and instructions issued by Techno Games Online, They are assigned in particular Comply with prevailing data protection laws. With regard to the processing of personal data, it remains Techno Games Online Party responsible. And if they decide Techno Games Online You breach contractual obligations, such as use Unauthorized versions of texts, retains Techno Games Online Explicitly merging an address IP With your other Data done by Techno Games Online Store them to provide advice on such infringements. It can be played Techno Games Online More action against a particular user to restore the normal operation of the games.");
define("SMALLHEAD_5", "F - internal search");
define("TEXT_7", "Used Techno Games Online Also information that is stored by you or about you in the internal search regarding Demographics, user interest and user behavior. These data are used anonymously. And you can Objection to this collected and stored data at any time in the future. Please send the email Of the denunciation referred to below. There will be no additional costs due to the withdrawal of approval, other than costs Cancel approval cancellation.");
define("SMALLHEAD_6", "G - Payment Processing");
define("TEXT_8", "You will need to provide additional information when making the payment. The nature of this data depends on the type of payment method that is You will select them. Offers Techno Games Online A large sector of the means of payment is not specified. You will Techno Games Online Passes the data required to process the payment to the service providers responsible for Collect payment. You will Techno Games Online Authorization (G2A.COM Limited, 36 / F, Tower Two, Times Square, 1 Matheson Street, Causeway Bay, Hong Kong Incorporation number: 2088957 Business registration number: 63264201) (To provide payment services. Cooperation with third parties also handles payments by providers Foreign payment services) PayPal, Credit card companies, mobile operators networks, etc. (. It is the responsibility Legal on these other parties in the processing of personal data confidential and secure manner in line with the prevailing legislation, You can only use these personal data in the implementation of their contractual obligations. When the payment is initiated during play, the cookie containing the issued ID number will be assigned At random. This cookie will be requested to return the game to you as soon as processing is completed paying off.
<br/>And employ Techno Games Online Individuals carrying responsibility ensure compliance with the proper implementation of the payment process, and therefore They can access any information necessary to do so. Specially trained personnel work exclusively In line with the texts and instructions issued by Techno Games Online, They are specifically charged with complying with the laws Prevailing data protection. These employees use anonymous payment data to detect and prevent abuse Use for payments. In the event of any breach, it will be canceled the payment process. Moreover, possess Techno Games Online The right to use any available data and enter personal data for further action If necessary.");
define("MIDDLEHEAD_4", "3. Technical features");
define("SMALLHEAD_7", "A - cookies");
define("TEXT_9", "Cookies are small files that enable Techno Games Online From recording specific information about Your device, for example, recognizes you when you re-visit the website or help collect statistics. Most cookies are automatically deleted when you close your browser or sign out of any website The game is managed by Techno Games Online. However, it can be some link files are stored for longer periods. This has been explained in detail in the previous sections on how to use Techno Games Online For profiles Link.");
define("SMALLHEAD_8", "B - Network counters");
define("TEXT_10", "Used Techno Games Online Network(, known as Photo counters GIF Or hel network, etc. ). Meter network A link placed on a website that refers to a small drawing image. When the website is requested With a linked link, an official photo will be requested automatically. Used Techno Games Online Network counters To optimize websites and ad campaigns by counting and storing traffic to a specific location, and if it's opened E - mail and when, etc.. The sections above describe in detail how to use Techno Games Online For counters feature the network.");
define("SMALLHEAD_9", "C - Additional social functions");
define("TEXT_11", "Techno Games Online uses social add-ons on their websites and games, such as Like button at Facebook or Facebook Connect And a button Google +1 at Google. This feature works Shared social add-ons when you access the company's website Techno Games Online Which uses social add-ons, the same data will be routed to the additional service provider These data will also be directed to the website of the service provider directly. As a way Example When calling a website of a service provider that has a Like button in Facebook, Will receive Facebook IP address Browser version, screen resolution, and operating system of the device you are using to access To the site, the address URL For the website that has the Like button. This applies even if you do not use any of the Services provided by the service provider. If social add-ons are provided by Facebook or Google, It will be previously mentioned data to the United States directed. Additional information will be directed if you log on to one of these services and / or use the functionality Social benefits while accessing the website. Please consult the associated service provider for the data Will be passed in this case.");
define("SMALLHEAD_10", "E - Program Google Analytics");
define("TEXT_12", "Used Company Techno Games Online Web Optimizer Google Analytics Websites and games And the main pages of their games. It uses a program Google Analytics Cookies) cookies (in order to We were able to post your visit to the games and sites run by the company Techno Games Online. To do so, the program combines Google Analytic s Data using page displays, any technical characteristics of the device used to visit Pages and activities on websites and games run by a company Techno Games Online. Then a program Google Analytic s Analyzes the data within the scope of the contractual functions of the company Techno Games online To collect reports including In that required information on URL Website, website or game Techno Games Online That has been visited, and how long the user stays on the website or game  Techno Games online And identification of activities Used throughout the visit. The company has Techno Games Online Configure a tool Google Analytics in which The last eight digits of the address will be deleted IP Before you are stored in Europe. You can opt out of using profiles Link) cookies ( In your browser settings, but remember that this will also restriction use any of the games Or company sites Techno Games Online. Alternatively, you can download the relevant plugins and install them in Your browser via this link: ) Https://tools.google.com/dlpage/gaoptout?hl=de ) It will receive code Google Analytics JavaScript Help not send any information about your visits to Games and sites Techno Games Online To a program Google Analytics.");
define("SMALLHEAD_11", "F - pop-up notifications");
define("TEXT_13", "If you have activated the appropriate settings on your mobile device, you may be sent Techno Games Online Notifications to your mobile device to share updates to games and other related news. Manage notifications Pop-up menu in the Options or Settings page in your mobile application or in your device settings.");
define("MIDDLEHEAD_5", "4. Cancel approval");
define("TEXT_14", "You may withdraw your consent at any time provided that you do so Techno Games Online Processing personal data with your consent For contractual or legal purposes. If the withdrawal of approval is related to the receipt of game information or any e-mail messages Other, all game information or other e-mail messages have the option to unsubscribe from any Game information or e-mail messages. There will be no additional costs due to the withdrawal of approval, other than Transfer cancellation costs.");
define("MIDDLEHEAD_6", "5. Edit or delete personal data");
define("TEXT_15", "Completely personal. Loose note that Techno Games Online You will not be able to commit to a survey request if it is like This request is inconsistent with any record keeping or other legitimate interests Techno Games online or Other Parties. If you wish to do Techno Games Online Modify your personal data or stop using Please contact us Techno Games Online On 
admin@xtatar.com. will rise Techno Games Online After implementing the required changes or delete your data as soon as possible. However, it should remind you Techno Games Online That, for technical or organizational reasons, there are some Procedures that are still to be done after the submission of the survey asked, in case if these measures have become but did not end With the passage of time.");
define("MIDDLEHEAD_7", "6. Information about personal data");
define("TEXT_16", "Upon request, will notify you Techno Games Online That all of your personal data that is registered is free the cost. This information will be sent to you in electronic form, usually via email.");
define("MIDDLEHEAD_8", "7. Disable your ID tracking");
define("TEXT_17", "For Apple: Open the settings on your mobile device) for iPhone or iPad (and select data security list. You can trace disabled under Propaganda. Not endowed Andrew hands : Open Settings in the apps list on the Ads button. There you can disable an ad ID Google Once the ad window is opened.");
define("MIDDLEHEAD_9", "8. Concluding texts");
define("TEXT_18", "Retains Techno Games Online The right to amend such privacy policy at any time, however, shall be taken into account Techno Games Online Always applicable data protection legislation. If you have any general questions about this privacy policy and protect your data at Techno Games Online, Kindly Contact the address below. If possible, please contact us by e-mail address provided when registering in the game.");
define("MIDDLEHEAD_10", "9. Company Data");
define("TEXT_19", "E-mail: admin@xtatar.com
<br/>For postal address:
<br/>Techno Games Online
<br/>13 Saad Ibn Abi Waqas St., El Haram, Giza, Egypt
<br/>Dated: October 3 / August 2017");
?>