<?php
define("BIGHEAD","Terms and Conditions");
define("MIDDLEHEAD_1","General Terms and Conditions");
define("TEXT_1","This game is operated by Techno Games Online, 13 Saad Bin Abi Waqas St., El Haram, Giza, Egypt,  The services pro-vided within the framework of this game are provided exclusively on the basis of these Terms and Conditions (the “terms”).");
define("MIDDLEHEAD_2","General information:");
define("TEXT_2","The operator of the game and the website is Techno Games Online (Commercial Registration No : 96623), 13 Saad Bin Abi Waqas St., El Haram, Giza, Egypt.
<br/>Managing Director: Ahmed Elewa
<br/>In the event of any problems with the website, the game or the purchase of credits, you can reach our customer service at admin@xtatar.com. This shall not incur any costs with the exception of those associated with sending the email. Customer service will usually respond to your inquiry within 24 hours. You may only communicate with customer service in the language of the relevant game world of the game.
<br/>The statutory liability for defects shall apply; only the claim to compensation is limited in accordance with § 13. Please also note §§ 12 and 13 with additional information in this connection.");
define("MIDDLEHEAD_3","1. Scope of application");
define("TEXT_3","(1) We hereby expressly object to the applicability of any terms and conditions of the users of the games (hereinafter “user”). Any terms and conditions of users shall only apply if TECHNO GAMES ONLINE has provided its previous written consent.
<br/>(2) In addition to these terms, the relevant applicable game rules, the relevant applicable rules of the forums applicable, the data protection regulations and the game instructions displayed on the website of the game shall apply.
<br/>(3) These terms are published exclusively on the websites of the game. The user can also download and save them onto their hard disk, store them on a permanent data carrier or print them out. These terms have also been saved by TECHNO GAMES ONLINE.
<br/>(4) The terms apply to all users of the game. Once the user has accepted the game user contract, he accepts such as binding. When registering for the game the user will be asked to accept the terms, which shall apply to any use of the game.
<br/>(5) TECHNO GAMES ONLINE offers the game solely to consumers as defined by § 13 . Use of the game for profit-making or other commercial purposes is prohibited. Only persons aged 18 years at the time of registration are entitled to participate in the game. Minors are only entitled to participate in the game if the consent of their legal representative has been granted prior to registration for the game. When registering, the user expressly confirms that he has reached the age of 18 and, for minors, that the consent of their legal representative has been obtained. TECHNO GAMES ONLINE may determine that the consent of the legal representative does not suffice.");
define("MIDDLEHEAD_4","2. Amendment to the terms by TECHNO GAMES ONLINE");
define("TEXT_4","(1) TECHNO GAMES ONLINE reserves the right to amend or supplement these terms at any time to take effect in the future should this be considered necessary on justifiable grounds (in particular to adapt them to comply with changes to the legal status and legislation or to new technological developments, to close any regulatory loopholes and to expand the scope of services of TECHNO GAMES ONLINE). Should such amendment substantially disrupt the contractual balance between the parties, the amendment shall be omitted.
<br/>(2) The user shall be notified of any amendments to these terms in an appropriate manner. Such notification shall either be carried out on the TECHNO GAMES ONLINE website, whereby a new window will appear when the user logs into the launch page or game platform, by sending an in-game message to the user's own game account or by email to the email address specified by the user. In all cases, the user shall also be informed of the amendment through a highlighted notification the next time he logs into the website or starts the game.
<br/>(3) The user can object to the amendments to the terms in writing within one (1) month after the notification and accessibility of the information, i.e. by sending an email to admin@xtatar.com to state the objection.
<br/>(4) Should the user not object to the amended terms within a period of one (1) month after the notification and the accessibility of the information to TECHNO GAMES ONLINE, the amended or supplemented terms shall become binding.
<br/>(5) Should the user object within the period of notice, TECHNO GAMES ONLINE shall be entitled to terminate the contract with no prior notice, resulting in the deletion of the game account. The original terms shall continue to be valid up until the time of the termination of the contract. In this event, the user may demand that the fee paid for credits previously activated but not used (see §§ 5 and 6) be reimbursed or that such credits be transferred to another game world; Credits shall be transferred only to game worlds of the same game and country version where the Credits have been purchased. The user can request reimbursement of credits allocated to premium features (see § 9) that were activated and for which the period of use had not yet commenced at the time the game or game world was dis-continued. The credits allocated to previously activated premium features for which the period of use had commenced at the time the game or game world was discontinued will not be reimbursed.
<br/>(6) In the notification of the amendments, TECHNO GAMES ONLINE will specifically draw the user’s attention to right to object and terminate the contract, the period of notice and the legal consequences, in particular the consequences of a failure to object.");
define("MIDDLEHEAD_5","3. Description of the service");
define("TEXT_5","(1) The service of TECHNO GAMES ONLINE consists in the provision of the websites of the game and the provision of the game itself. TECHNO GAMES ONLINE offers the game to users free of charge in a manner that enables the game to be played; only the game itself is free of charge, the user is responsible for any additional costs (e.g. for the transmission of data, hardware and software). In addition, TECHNO GAMES ONLINE enables the user to purchase credits for a fee which entitle the user, at his discretion, to activate premium features which provide additional functions and game options, and may create advantages in the game and in the gaming activities. Credits only apply to the game, the relevant national game world and to the game account from which they were purchased. Credits cannot be ex-changed or returned. Please see §§ 5 and 6 for more details on credits and § 9 for more details on premium features.
<br/>(2) The use of the game is only available to users who have accepted a game user contract. The use of the game is enabled from the time a game user contract has been entered into. For this purpose, the user will receive a single, non-transferable right to use the free functions of the game in its current version. The user is not automatically entitled to a game user con-tract. Notwithstanding different regulations that apply to each game or game world, the user may only have one game account. Please see § 4 for more details regarding the conclusion of a game user contract.
<br/>(3) The game and the game worlds, the value of the credits and the premium features are continuously updated, amended, extended and modified to ensure the game retains the interest of as many users as possible in the long term. Therefore, the user only obtains a right to use the game, cred-its and premium features in their current version at a given time. The user has no right to request retention of the game, credits and premium features in the version current at the time of accepting the contract.
<br/>(4) At the discretion of TECHNO GAMES ONLINE, the game is subdivided into individual game worlds. The game and individual game worlds are organized in game rounds or as a continually developing game at the discretion of TECHNO GAMES ONLINE. The respective game world will be reset at the end of a game round. The user is not entitled to keep the game situation or position he has reached at this time or to have it transferred to a different game world. Nor is the user entitled to transfer his game account to an-other game world. The term “game round” will also be used below if the game is designed as a continually developing game over the long term; in this case the term “game round” is intended to mean the “duration of the game”. The same principle applies to the term “game world”.
<br/>(5) At the end of the game round, the user may request that any previously activated but unused credits be transferred to another game world; Cred-its shall be transferred only to game worlds of the same game and country version where the Credits have been purchased. The credits allocated to previously activated premium features for which the period of use had not yet commenced at the time the game or game world was discontinued, will be reimbursed. The credits allocated to previously activated premium features for which the period of use had commenced at the time the game or game world was discontinued will not be reimbursed.
<br/>(6) The transfer of credits will take place by sending an email. The user shall be responsible for ensuring that he does not lose the email.
<br/>(7) TECHNO GAMES ONLINE reserves the right to discontinue the operation of the game or of individual game worlds at any time without having to state the grounds for such. TECHNO GAMES ONLINE will provide appropriate prior notice of the discontinuation of the game or the game world operation.");
define("MIDDLEHEAD_6","4. Conclusion of the game user contract via registration or download");
define("TEXT_6","(1) Membership commences upon conclusion of a game user contract for a game world by TECHNO GAMES ONLINE.
<br/>(2) By completing the registration form or starting the download process of the game in an app store, the user makes a binding offer to enter into a game user contract for an indefinite period.
<br/>(3) The user must register personally. Registration by third parties, in particular third parties who register individual persons with various tele media providers for commercial purposes (registration services or entry services), is not permitted.");
define("MIDDLEHEAD_7","5. Purchasing credits");
define("TEXT_7","(1) TECHNO GAMES ONLINE will provided the user a service in the game that enables him to unlock premium features (“credits”) (§ 9). Credits are a game unit that allows the user to unlock premium features. Credits are purchased by the user for a fee and can also, at the discretion of TECHNO GAMES ONLINE, be unlocked by certain actions the user carries out in the game.
<br/>(2) The user has the option of accessing the game shop via the credits symbol, where a range of credit packages are available to purchase at varying costs. All offers presented there are non-binding and only represent an invitation to place an order. Once the user has clicked to select a credit package, he can then choose one of the payment methods available (e.g. credit card, debit mandate etc.). In addition to the various payment methods, information is displayed on the period in which the credits will be credited. The key contract information is also summarized again at a further stage. Here the user has the opportunity to identify and correct any input errors by changing the package size or payment method for in-stance. The user can cancel this order process at any time without con-sequences by closing the window and restarting the process. A binding offer for the purchase of the credit package selected is given to the user once he clicks the “Buy” button. Another page also opens when the user clicks the “Buy” button where the user must enter all the information required to transact the payment. The credits purchased will be credited immediately after the payment is verified.
<br/>(3) TECHNO GAMES ONLINE is permitted to request advance payment for the purhase of credits.
<br/>(4) When you use G2A Pay services provided by G2A.COM Limited (hereinafter referred to as the G2A Pay services provider) to make a purchase on our website, responsibility over your purchase will first be transferred to G2A.COM Limited before it is delivered to you. G2A Pay services provider assumes primary responsibility, with our assistance, for payment and payment related customer support. The terms between G2A Pay services provider and customers who utilize services of G2A Pay are governed by separate agreements and are not subject to the Terms on this website.  
With respect to customers making purchases through G2A Pay services provider checkout, (i) the Privacy Policy of G2A Pay services provider shall apply to all payments and should be reviewed before making any purchase, and (ii) the G2A Pay services provider Refund Policy shall apply to all payments unless notice is expressly provided by the relevant supplier to buyers in advance. In addition the purchase of certain products may also require shoppers to agree to one or more End-User License Agreements (or EULAs) that may include additional terms set by the product supplier rather than by Us or G2A Pay services provider. You will be bound by any EULA that you agree to.
We and/or entities that sell products on our website by using G2A Pay services are primarily responsible for  warranty, maintenance, technical or product support services for those Products. We and/or entities that sell products on our website are primarily responsible to users for any liabilities related to fulfillment of orders, and EULAs entered into by the End-User Customer. G2A Pay services provider is primarily responsible for facilitating your payment. 
You are responsible for any fees, taxes or other costs associated with the purchase and delivery of your items resulting from charges imposed by your relationship with payment services providers or the duties and taxes imposed by your local customs officials or other regulatory body.
For customer service inquiries or disputes, You may contact us by email at admin@xtatar.com
Questions related to payments made through G2A Pay services provider payment should be addressed to support@g2a.com. 
Where possible, we will work with You and/or any user selling on our website, to resolve any disputes arising from your purchase.
 
<br/>(5) The number of credits to be allocated, the game money to be used and the conditions of the respective premium features are displayed in the appropriate list in the game.
<br/>(6) TECHNO GAMES ONLINE does not store the contract text for orders. However, users shall receive email confirmation of their order, which contains the text of the contract. The language available for the text of the contract is the respective language of the game world of the game.
<br/>(7) The value of credits varies according to the tariff chosen and can be modified at any time. The prices stated on the website at the time of the or-der shall apply. All prices are given including the value added tax (insofar as value added tax is levied). Dispatch costs are not incurred. The cur-rent technical and other requirements are listed on the game's website.
<br/>(8) Should TECHNO GAMES ONLINE incur any chargeback costs or cancelations arising from the user’s conduct, TECHNO GAMES ONLINE shall suspend any services and block the user’s game account with immediate effect. The user’s obligation to pay any outstanding fees shall remain unaffected. The user may unlock his account upon payment of the fees due, plus a processing fee. The user shall also bear any costs for the repayment of the fees due and chargeback costs. The chargeback costs shall be in a sum equivalent to €5. The user may provide evidence that no damages or costs were incurred or that such were substantially lower. Game accounts cannot be unlocked in the following countries: Egypt, Algeria, Armenia, Azerbaijan, Bahrain, Djibouti, Indonesia, Iraq, Yemen, Jordan, Qatar, Kuwait, Leba-non, Libya, Morocco, Mauretania, Oman, Autonomous Palestinian Territories, Saudi Arabia, Somalia, Sudan, Tunisia, United Arab Emirates, Vietnam and Western Sahara.
<br/>(9) Any credits for activated premium features whose period of use had commenced shall be reimbursed proportionately for the duration of the blocking of the account. Thus any benefits the user has obtained from the premium features while his account was blocked will be incorporated through the reimbursement.");
define("MIDDLEHEAD_8","6. Right to use credits");
define("TEXT_8","(1) When the user’s game account is credited with credits, the user is granted a single right of use for the credits purchased for the duration of the game round. Regarding the transfer of credits, the term “sell” shall mean the “transfer to the user of a single, non-transferable right of use for the credits for the duration of the game round, for which a return service must be provided”, unless otherwise stipulated in the wording or context
used. The term “buy” therefore means the “acquisition by the user of a single, non-transferable right of use for the credits for the duration of the game round”. The terms “buyer”, “seller”, “sale” and “purchase” and similar terms have corresponding meanings.
<br/>(2) Credits are only valid for the relevant national game world from which they are purchased or to which they have been transferred. The user acknowledges that credits are solely a game function and are not real money. Any trading or exchange of credits for real money is expressly prohibited. Any exchange for real money or return of credits is not per-mitted, except in the cases stipulated in § 2 (5) sentence 3 and § 7, and irrespective of the liability and warranty regulations as well as any right to revocation.
<br/>(3) Notwithstanding any other agreements and the rights of TECHNO GAMES ONLINE, the right to use credits shall end in any case when the existing game user contract between TECHNO GAMES ONLINE and the user expires, in particular if such contract is terminated. In this event, the user may request that any previously activated but unused credits be transferred to another game world; Credits shall be transferred only to game worlds of the same game and country version where the Credits have been purchased.");
define("MIDDLEHEAD_9","7. Notice of revocation");
define("TEXT_9","Right of revocation
You have the right to withdraw from the game user contract and the contract for the purchase of credits within fourteen days without specifying a reason.
The revocation period commences fourteen days from the day of con-tract conclusion.
To exercise your right to revocation, you need to inform us (Techno Games Online, 13 Saad Bin Abi Waqas St., El Haram, Giza, Egypt, Tel +201275545187 , admin@xtatar.com) by means of a clear declaration (such as via letter sent by post,  email) of your intention to withdraw from the contract. You may use the attached revocation form template but are not obligated to do so.
In order to observe the revocation period, it is deemed sufficient that you send the notice regarding the exercise of the right to revocation prior to the expiration of the revocation period.
Consequences of revocation
In the event you have withdrawn from this contract, we undertake to return all payments we have received by you, including delivery costs (with the exception of additional costs that have arisen due to your choice of a different mode of delivery than the cheapest standard delivery offered by us) without delay and no later than fourteen days from the date we receive your notice regarding your withdrawal from this contract. In order to settle this return payment, we shall use the same payment method that you originally used for the original transaction, unless we have expressly come to a different agreement with you; under no circumstances shall any fees associated with this return payment be charged to you.
End of the notice of revocation
<br/>Revocation form template
(In the event you wish to withdraw from this contract, please complete this form and send it back to us.)
- To: Techno Games Online, 13 Saad Bin Abi Waqas St., El Haram, Giza, Egypt, Tel +201275545187 , admin@xtatar.com:
I/we (*) hereby withdraw from the contract I/we (*) concluded for the purchase of the following items (*) / the rendering of the fol-lowing services (*)
- Ordered on (*)/received on (*)
- Name of the consumer(s)
- Address of the consumer(s)
- Signature of the consumer(s) (only for declaration in paper form)
- Date
(*) Delete as appropriate.
<br/>Special notice:
The right to revocation shall expire prematurely for contracts for the de-livery of digital content not stored on a physical data carrier, if TECHNO GAMES ONLINE has already begun executing the contract, after the user
<br/>1. has given its express consent that TECHNO GAMES ONLINE may begin execution of the contract before expiry of the revocation period, and
<br/>2. has acknowledged that it shall lose its right to revocation by providing its consent to start contractual execution.
When sending a notice of revocation via email, the user is advised to state the username, game account and the game world in the subject line of the email.");
define("MIDDLEHEAD_10","8. Offsetting, rights of retention");
define("TEXT_10","The user may only offset counterclaims against receivables due from TECHNO GAMES ONLINE if such are undisputed or legally established. The user may only exercise a right of retention if his counterclaim relates to the same contract. The user may not assign any claims against TECHNO GAMES ONLINE to third parties.");
define("MIDDLEHEAD_11","9. Premium features");
define("TEXT_11","(1) Credits enable the user to unlock premium features during the game. TECHNO GAMES ONLINE reserves the right to require that game money (§ 10) be used to unlock premium features.
<br/>(2) TECHNO GAMES ONLINE offers premium features for the game to its users at its discretion. In particular, premium features may include the following:
• Item: Virtual item which is available to the user during the game round (e.g. furniture);
• Artifact: Virtual item which is available to the user during the game round or for a shorter period and provides one or more advantages for the user during the game (e.g. armor with special features);
• Buff: Additional function which provides one or more one-off ad-vantages for the user during the game (e.g. calling NPC (“non-player character”) traders);
• Boost: Additional function which provides one or more advantages for the user during the game for a certain period (e.g. improved ex-traction of raw materials);
• Premium membership: Additional function which enables the user to have an extended range of game functions (e.g. access to statis-tics);
• Trading Cards: Virtual collecting cards which represent a random compilation of premium features of the same or different type; each Trading Card represents a premium feature;
• Wheel of fortune: Purchase of a randomly selected premium feature using credits or game money.
The website of the relevant game world shows the premium features available, the tariff, their functionalities and what is required for them. TECHNO GAMES ONLINE reserves the right to introduce new premium features.
<br/>(3) Insofar as TECHNO GAMES ONLINE offers Trading Cards, TECHNO GAMES ONLINE shall ensure that the value of the Trading Cards acquired is equivalent to the credits allocated. TECHNO GAMES ONLINE reserves the right to make a system available for the game or individual game worlds within which the user can exchange individual or several of the Trading Cards he has acquired for one or several new Trading Cards and/or credits.
<br/>(4) Insofar as TECHNO GAMES ONLINE offers a wheel of fortune, TECHNO GAMES ONLINE shall ensure that the value of the premium features acquired is at least equivalent to the credits used.
<br/>(5) TECHNO GAMES ONLINE reserves the right to provide a platform to the users for the game or individual game worlds within which users can exchange premium features among one another or trade with them.
<br/>(6) TECHNO GAMES ONLINE reserves the right at any time to offer new premium features, to modify individual premium features or to cease offering them. In this event, TECHNO GAMES ONLINE will offer other features as a replacement and/or credit the credits allocated to the user at the user’s request had premium features been activated for which the period of use had not yet commenced at the time of the modification or at the time these are no longer offered in the future. Previously activated premium features for which the period of use had commenced at the time of the modification or the future failure to offer will not be reimbursed.
<br/>(7) If the game user contract existing between TECHNO GAMES ONLINE and the user ends (i.e. by a termination or the discontinuation of the game or a game world), previously activated premium features for which the period of use had commenced at the time of cancellation will not be reimbursed, even if their period of use had not yet expired. The user may request to be credited the credits for previously activated premium features for which the period of use had not yet commenced at the time of such termination.");
define("MIDDLEHEAD_12","10. Game money");
define("TEXT_12","TECHNO GAMES ONLINE may provide a service to the user in the game which simulates a means of payment within the game (“game money”). Game money is unlocked when the user carries out certain actions in the game. The user acknowledges that game money is solely a game function, and not real money. Any trade or exchange of game money for real money be-tween users is expressly prohibited. In any event, the exchange of game money for real money is not permitted.");
define("MIDDLEHEAD_13","11. Obligations of the user");
define("TEXT_13","(1) A user may not have several accounts for one game world simultaneously. However, the user is permitted to have one game account in several game worlds simultaneously. TECHNO GAMES ONLINE reserves the right to allow several game accounts per user for a game or individual game worlds. In this event, TECHNO GAMES ONLINE shall indicate this in an appropriate manner to the user.
<br/>(2) The user undertakes to comply with the laws and regulations applicable to him when using all the games and websites operated by TECHNO GAMES ONLINE. He undertakes to comply with the game rules applicable. Furthermore, he undertakes to refrain from the following actions:
• Dissemination of statements with abusive, harassing or violent content or with content glorifying violence or with inflammatory, sexist, obscene, pornographic, racist, morally reprehensible content or with other offensive or prohibited content (which includes all names within the game e.g. username, name of the avatar, name of the village, town, alliance, guild, tribe, clan, vehicle, island, association, etc.).
• The insulting, harassment, threatening, frightening behavior against, or defamation and embarrassment of other users.
• Dissemination of statements with advertising, religious or political content (which includes all names within the game e.g. username, name of the avatar, name of the village, town, alliance, guild, tribe, clan, vehicle, is-land, association, etc.).
• The spying, disclosure or dissemination of personal or confidential information of other users, employees of TECHNO GAMES ONLINE or any other disregard of the private sphere of other users or employees of TECHNO GAMES ONLINE.
• Dissemination of untruthful allegations about the race, religion, sex, sexual orientation, origin, social status of other users or employees of TECHNO GAMES ONLINE (which includes all names within the game e.g. username, name of the avatar, name of the village, town, alliance, guild, tribe, clan, vehicle, island, association, etc.).
• The spying out, disclosure or dissemination of confidential information of TECHNO GAMES ONLINE.
• Dissemination of untruthful allegations about TECHNO GAMES ONLINE (which includes all names within the game e.g. username, name of the avatar, name of the village, town, alliance, guild, tribe, clan, vehicle, island, association, etc.).
• Pretending to be an employee of TECHNO GAMES ONLINE or an affiliated company or partner of TECHNO GAMES ONLINE.
• Use of legally protected pictures, photos, graphics, videos, music tracks, sounds, text, brand names, titles, names, software or other content with-out the consent of the holder(s) of the rights or having permission to do so by law or legal provision.
• Use of prohibited or illegal content.
• Use of errors in the programming (bugs).
• Actions leading to an overload of the servers and/or can considerably adversely affect the game play for other users.
• Hacking or cracking and the encouragement or incitement to carry out hacking or cracking.
• Dissemination of pirated software and the encouragement or incitement to disseminate pirated software.
• Uploading of files containing viruses, Trojan horses, worms or destroyed data.
• Use or dissemination of “auto” software programs, “macro” software pro-grams or other “cheat utility” software programs.
• Modification of the game, the websites of the game or parts thereof.
• Use of software that enables what is referred to as “data mining” or in any other manner intercepting or gathering information related to the game.
• Disruption of transmissions from and to the game servers and the website servers of the game.
• Disruption of transmissions from and to the game servers and the website servers of the game.
<br/>(3) The user undertakes to comply with the rules of the game.
<br/>(4) TECHNO GAMES ONLINE only provides a platform for communication between players; the user is responsible for the content of such communication. The platform is solely provided for communication regarding the game. The flooding of the communication platform with messages, chain letters, snowball systems or any other form of spamming is strictly forbidden.
<br/>(5) The user is only entitled to use the game via common web browsers. Any additional use via additional programs, scripts or other supporting tools is expressly prohibited.
<br/>(6) The games and game worlds are intended to provide as much fun for all users for as long as possible. TECHNO GAMES ONLINE is therefore anxious that users comply with stipulations (1) to (5) of such rules and obligations. TECHNO GAMES ONLINE therefore reserves the right to use the appropriate pro-grams and trained personnel to detect any such contractual violations by the user, and to identify the user in the event of any reasonable suspicion of a breach of contract. Users are expressly advised to consult the TECHNO GAMES ONLINE Privacy Policy.
<br/>(7) Violation of any of the rules and obligations set out in (1) to (5) may be punished with the withdrawal of the game progress and/or an immediate temporary block on the game account, depending on the nature of the violation. Should a violation be detected, one of the appropriately trained TECHNO GAMES ONLINE employees shall decide in good faith on the consequences of such violation in each individual case. The user accepts that the decision of the employee is final. In addition, the user accepts that TECHNO GAMES ONLINE cannot disclose the mechanisms used for detecting violations, as such mechanisms could be easily circumvented.
<br/>(8) Violation of any of the rules and obligations set out in (1) to (5) may, after a prior warning notice, lead to an immediate block or deletion of the game account or a termination with immediate effect of the game user contract on justifiable grounds. In the event of serious violations, a warning is not necessary. A violation is considered serious particularly if, when considering all the facts and circumstances of the individual case and taking the interests of both TECHNO GAMES ONLINE and the user into account, TECHNO GAMES ONLINE cannot be reasonably expected to anticipate further violations.
<br/>(9) TECHNO GAMES ONLINE reserves the right to prohibit the user to register for the game again in future following a permanent block or deletion of the game account or an extraordinary termination of the game user contract.
<br/>(10) The user must ensure that the access password he received remains secret and, for security reasons, change his password regularly. Should a third party access the user’s game account after acquiring the access data because the user failed to adequately secure such data from access by other users, the user shall be treated as if he himself had acted. The user is entitled to provide evidence that he has not acted, and that he has adequately secured the game account from access by other users.
<br/>(11) Unless otherwise specified in these terms or in any other agreement with the user, TECHNO GAMES ONLINE shall normally communicate with the user by email. The user shall ensure that he receives emails sent by TECHNO GAMES ONLINE to the email address supplied by the user at the time of registration or at a later date. This shall be ensured by appropriate settings of the spam filter and by checking the relevant email address regularly. In other respects TECHNO GAMES ONLINE reserves the right to select the form of correspondence for any other written communication.
<br/>(12) When the user contacts TECHNO GAMES ONLINE, the user is advised to state his player's name, the game world and the game account to which his inquiry refers.");
define("MIDDLEHEAD_14","12. Game defects");
define("TEXT_14","(1) TECHNO GAMES ONLINE provides use of the game and the websites of the game to the user in the version existing at the respective point in time. Without prejudice to any claims in the event of defects in the game or in the websites of the game, the user is not entitled to request that a certain state and/or functional scope of the game be retained or established.
<br/>(2) As a contribution to the correct operation of the game, the user is advised to always appropriately document any defects that occur in the game or in any other deliveries or services of TECHNO GAMES ONLINE and, in particular, to report them, documenting any error messages that occur.
<br/>(3) For the user's own protection, and in particular for reasons of securing evidence, the user is recommended to direct any notices of defects in writing to TECHNO GAMES ONLINE.
<br/>(4) TECHNO GAMES ONLINE shall not assume any guarantees in the legal sense, un-less expressly otherwise agreed in writing.");
define("MIDDLEHEAD_15","13. Liability of TECHNO GAMES ONLINE");
define("TEXT_15","(1) In the event the user does not purchase any credits for a money fee during its use of the game, TECHNO GAMES ONLINE shall only be liable for damages incurred through the contractual use of the game and only in the case of content (including bad faith) and gross negligence. In cases of legal defects TECHNO GAMES ONLINE shall also only be held liable for defects that were fraudulently concealed. Otherwise paragraphs (5) to (8) shall apply.
<br/>(2) From the time at which the user purchased credits for a money fee during its use of the game, the regulations of the following paragraphs (3) to (8) shall apply for the liability of TECHNO GAMES ONLINE until the end of the respective game round in which the user purchased the credits for a money fee.
<br/>(3) TECHNO GAMES ONLINE shall have unlimited liability in the event of intent and gross negligence. In addition, TECHNO GAMES ONLINE is further liable for the negligent breach of essential contractual obligations. Essential contractual obligations are defined as such obligations that enable the proper implementation of the contract possible in the first place, the breach of which jeopardizes the fulfillment of the object of the contract and the fulfillment of which the user may rely on. In the latter case, however, TECHNO GAMES ONLINE is not liable for damage which is not typical and could not before seen. The limitation period for claims stipulated in sentences 2-4 is two years. TECHNO GAMES ONLINE is not liable for any simply negligent breach of other obligations.
<br/>(4) The foreseeable damage is restricted in terms of amount to €100 per game account.
<br/>(5) The limitations and exclusions of liability above shall not apply for the concealment of a defect in bad faith, in the event of death, physical injury and impairment of health or in the event that TECHNO GAMES ONLINE accepts a guarantee. The liability of TECHNO GAMES ONLINE based on the Product Liability Act remains unaffected.
<br/>(6) In other respects, any liability for the recovery of the user's data is restricted in terms of amount to the costs required to recover data which would have been lost even if reasonable data back-up measures had been carried out on a regular basis or which can be recovered from machine-readable data material at a reasonable expense even if no reasonable da-ta back-up measures were carried out in any other manner on a regular basis.
<br/>(7) The limitations and exclusions of liability above shall also apply with regard to the liability of the legal representatives, vicarious agents and employees of TECHNO GAMES ONLINE.
<br/>(8) Any amendment to the burden of proof to the disadvantage of the user is not bound by the abovementioned regulations.");
define("MIDDLEHEAD_16","14. Contract duration, termination");
define("TEXT_16","(1) The contracts between the user and TECHNO GAMES ONLINE relating to the use of the basic version of the game worlds are for an indefinite period unless otherwise determined in the specific offer of TECHNO GAMES ONLINE.
<br/>(2) The game user contract may be terminated at any time with immediate effect by both parties without having to state the grounds for such, unless a fixed term notice period has been expressly agreed.
<br/>(3) The right of the parties to a termination with notice of the game user contract on justifiable grounds remains unaffected by the provisions above. Extraordinary termination with no prior notice on justifiable grounds is only permitted when such grounds are stated.
<br/>(4) Without prejudice to § 11 (8), in particular TECHNO GAMES ONLINE is entitled to give notice of cancellation of the game user contract on justifiable grounds if:
• the user has not used his game account for a period described in detail in the game rules following notification of such from TECHNO GAMES ONLINE;
• the user exchanges or trades credits for real money.
<br/>(5) For technical reasons, a period of several days will elapse before the permanent deletion of the user's data and the game account.
<br/>(6) The termination of a game user contract and/or game account must be made in writing. Fax or email is also considered a valid written form.
<br/>(7) Should the game user contract be terminated, no exchange of game money for real money shall ensue; this also applies to credits, except as described in § 2 (5). Please see § 9 (7) regarding the conversion of previously activated premium features into credits in the event of a termination.
<br/>(8) In the event of the deletion of a game user account, the validity of the game user contract shall remain unaffected.
");
define("MIDDLEHEAD_17","15. Data protection, advertising");
define("TEXT_17","(1) TECHNO GAMES ONLINE shall handle all personal data which the user submits during the contractual relations strictly confidentially and in compliance with all relevant data protection regulations.
<br/>(2) For technical reasons, participation in the game and the game-related services is not possible without saving user data. The user agrees to the electronic saving and processing of his data by applying to open a game account or by using game related services.
<br/>(3) Should a user request the deletion of his data in its entirety, this shall automatically result in the deletion of all the game accounts he has created in the games operated by TECHNO GAMES ONLINE and the cancellation of the game user contract.
<br/>(4) In other respects, the TECHNO GAMES ONLINE Privacy Policy applies.");
define("MIDDLEHEAD_18","16. Final provisions");
define("TEXT_18","(1) These terms and all contracts accepted on the basis of these terms shall be subject to the laws of the Egyptian Arabic Republic. The application of the UN Convention on Contracts for the International Sale of Goods and the conflict of legal provisions of Egypt private international law are excluded.
<br/>(2) If the user has his place of residence or habitual place of abode outside the Egyptian Arabic Republic, the registered office of TECHNO GAMES ONLINE shall be the place of jurisdiction. This also applies if the user's place of residence or habitual place of abode is unknown at the time such legal action is instigated.
<br/>(3) Should provisions of these terms be invalid, this shall not affect the validity of the remaining provisions.");
define("MIDDLEHEAD_19","Company Data");
define("TEXT_19","Techno Games Online
<br/>13 Saad Bin Abi Waqas St, 
El Haram, Giza, Egypt
<br/>Commercial Registration No : 96623 
<br/>Managing Director: Ahmed Elewa
<br/>Email: admin@xtatar.com
<br/>Version: 3/10/2017");
?>