{function="load_lang('ui/custbuilds')"}

{if="( 0 < intval( $data['alliance_id'] ) )"}
<table cellpadding="1" cellspacing="1" id="ally_info">
    <thead>
        <tr>
            <th colspan="2">{#LANGUI_CUSTBU_EMB_t1}</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>
                {#LANGUI_CUSTBU_EMB_t2} :
            </th>
            <td>{$data.alliance_name}</td>
        </tr>
        <tr>
            <td colspan="2">
                <a href="alliance?id={$data.alliance_id}"> » {#LANGUI_CUSTBU_EMB_t3} </a>
            </td>
        </tr>
    </tbody>
</table>
{else}
{if="( 3 <= $embassyProperty['level'] )"}
<form method="post" name="snd" action="build?id={$buildingIndex}">
    <table cellpadding="1" cellspacing="1" id="found">
        <thead>
            <tr>
                <th colspan="2">{#LANGUI_CUSTBU_EMB_t4}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>
                    {#LANGUI_CUSTBU_EMB_t2} :
                </th>
                <td class="tag">
                    <input class="text" name="ally1" value="{$embassyProperty.ally1}" maxlength="8">
                    {if="( $embassyProperty['error'] == 1 || $embassyProperty['error'] == 3 )"}
                        <span class="error">{#LANGUI_CUSTBU_EMB_t5}</span>
                    {/if}
    
                    {if="( $embassyProperty['error'] == 6 )"}
                        <span class="error">{#LANGUI_CUSTBU_EMB_t15}</span>
                    {/if}
    
                    {if="( $embassyProperty['error'] == 4 )"}
                        <span class="error">{#LANGUI_CUSTBU_EMB_t6}</span>
                    {/if}
                </td>
            </tr>
            <tr>
                <th>
                    {#LANGUI_CUSTBU_EMB_t7} :
                </th>
                <td class="nam">
                    <input class="text" name="ally2" value="{$embassyProperty.ally2}" maxlength="25">
                    {if="( $embassyProperty['error'] == 2 || $embassyProperty['error'] == 3 )"}
                        <span class="error">{#LANGUI_CUSTBU_EMB_t8}</span>
                    {/if}
                </td>
            </tr>
        </tbody>
    </table>
    <p>
        <input type="image" value="ok" name="s1" id="btn_ok" class="dynamic_img" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#LANGUI_CUSTBU_EMB_t9}">
    </p>
</form>
{/if}
    <table cellpadding="1" cellspacing="1" id="join">
        <thead>
            <tr>
                <th colspan="3">{#LANGUI_CUSTBU_EMB_t10}</th>
            </tr>
        </thead>
        <tbody>
            {$_c = 0}
            {loop="$embassyProperty['invites']"}
                {$_c = $_c + 1}
                    <tr>
                        <td class="abo">
                            <a href="build?id={$buildingIndex}&d={$key}">
                                <img class="del" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#LANGUI_CUSTBU_EMB_t11}" title="{#LANGUI_CUSTBU_EMB_t11}">
                            </a>
                        </td>
                        <td class="nam">
                            <a href="alliance?id={$key}">{$value}</a>
                        </td>
                        <td class="acc">
                            <a href="build?id={$buildingIndex}&a={$key}">{#LANGUI_CUSTBU_EMB_t12}</a>
                        </td>
                    </tr>
            {/loop}
            
            {if="( $_c == 0 )"}
                <tr>
                    <td colspan="3" class="none">{#LANGUI_CUSTBU_EMB_t13}</td>
                </tr>
            {/if}
        </tbody>
    </table>
    {if="( isset( $embassyProperty['error'] ) && $embassyProperty['error'] == 15 )"}
        <b>
            <p class="error">{#LANGUI_CUSTBU_EMB_t14}</p>
        </b> 
    {/if}
{/if}