{function="load_lang('ui/custbuilds')"}
<div id="textmenu">
    <a href="build?id={$buildingIndex}" {if="( $selectedTabIndex == 0 )"} class="selected" {/if} >
        {#LANGUI_CUSTBU_MKT_p1}
    </a>
    |
    <a href="build?id={$buildingIndex}&t=1" {if="( $selectedTabIndex == 1 )"} class="selected"{/if} >
        {#LANGUI_CUSTBU_MKT_p2}
    </a>
    |
    <a href="build?id={$buildingIndex}&t=2" {if="( $selectedTabIndex == 2 )"} class="selected" {/if} >
        {#LANGUI_CUSTBU_MKT_p3}
    </a>
    |
    <a href="build?id={$buildingIndex}&t=3" {if="( $selectedTabIndex == 3 )"} class="selected" {/if}>
        {#LANGUI_CUSTBU_MKT_p4}
    </a>
</div>

{if="( $selectedTabIndex == 0 )"}
<script language="JavaScript">
    <!--
    var merchNum = {$merchantProperty.exits_num};
    var carry = {$merchantProperty.capacity};
    //-->
</script>
<div id="contract">
    <form method="post" name="snd" action="build?id={$buildingIndex}">
    {if="( !$merchantProperty['confirm_snd'] )"}
        <input type="hidden" name="act" value="1" />
        <table id="send_select" class="send_res" cellpadding="1" cellspacing="1">
            <tbody>
                <tr>
                    <td class="ico">
                        <a href="#" onclick="upd_res(1,1); return false;">
                            <img class="r1" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_1}" title="{#item_title_1}">
                        </a>
                    </td>
                    <td class="nam">
                        {#item_title_1}:
                    </td>
                    <td class="val">
                        <input class="text" type="text" name="r1" id="r1" value="{if="isset($_POST['r1'])"}{function="post('r1')"}{/if}" maxlength="8" onkeyup="upd_res(1)" tabindex="1">
                    </td>
                    <td class="max">
                        <a href="#" onmouseup="add_res(1);" onclick="return false;">
                            ({$merchantProperty.capacity})
                        </a>
                    </td>
                </tr>
                <tr>
                    <td class="ico">
                        <a href="#" onclick="upd_res(2,1); return false;">
                            <img class="r2" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_2}" title="{#item_title_2}">
                        </a>
                    </td>
                    <td class="nam">
                        {#item_title_2}:
                    </td>
                    <td class="val">
                        <input class="text" type="text" name="r2" id="r2" value="{if="isset($_POST['r2'])"}{function="post('r2')"}{/if}" maxlength="8" onkeyup="upd_res(2)" tabindex="2">
                    </td>
                    <td class="max">
                        <a href="#" onmouseup="add_res(2);" onclick="return false;">
                            ({$merchantProperty.capacity})
                        </a>
                    </td>
                </tr>
                <tr>
                    <td class="ico">
                        <a href="#" onclick="upd_res(3,1); return false;">
                            <img class="r3" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_3}" title="{#item_title_3}">
                        </a>
                    </td>
                    <td class="nam">
                        {#item_title_3}:
                    </td>
                    <td class="val">
                        <input class="text" type="text" name="r3" id="r3" value="{if="isset($_POST['r3'])"}{function="post('r3')"}{/if}" maxlength="8" onkeyup="upd_res(3)" tabindex="3">
                    </td>
                    <td class="max">
                        <a href="#" onmouseup="add_res(3);" onclick="return false;">
                            ({$merchantProperty.capacity})
                        </a>
                    </td>
                </tr>
                <tr>
                    <td class="ico">
                        <a href="#" onclick="upd_res(4,1); return false;">
                            <img class="r4" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_4}" title="{#item_title_4}">
                        </a>
                    </td>
                    <td class="nam">
                        {#item_title_4}:
                    </td>
                    <td class="val">
                        <input class="text" type="text" name="r4" value="{if="isset($_POST['r4'])"}{function="post('r4')"}{/if}" id="r4" maxlength="8" onkeyup="upd_res(4)" tabindex="4">
                    </td>
                    <td class="max">
                        <a href="#" onmouseup="add_res(4);" onclick="return false;">
                            ({$merchantProperty.capacity})
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>
        <table id="target_select" class="res_target" cellpadding="1" cellspacing="1">
            <tbody>
                <tr>
                    <td class="mer">
                        {#LANGUI_CUSTBU_MKT_p1_t1}
                        {$merchantProperty.exits_num}
                        /
                        {$merchantProperty.total_num}
                    </td>
                </tr>
                <tr>
                    <td class="vil">
                        <span>
                            {#LANGUI_CUSTBU_MKT_p1_t2} :
                        </span>
                        <input class="text" type="text" name="vname" value="{if="isset($_POST['vname'])"}{function="post('vname')"}{/if}" maxlength="20" tabindex="5">
                    </td>
                </tr>
                <tr>
                    <td class="or">{#text_or_lang}</td>
                </tr>
                <tr>
                    <td class="coo">
                        <span>X:</span>
                        <input class="text" type="text" name="x" value="{if="isset($_POST['x'])"}{$_POST['x']}{/if}" maxlength="4" tabindex="6">
                        <span>Y:</span>
                        <input class="text" type="text" name="y" value="{if="isset($_POST['y'])"}{$_POST['y']}{/if}" maxlength="4" tabindex="7">
                    </td>
                </tr>
            </tbody>
        </table>
        <script language="JavaScript" type="text/javascript">document.snd.r1.focus();</script>
        {else}
        <input type="hidden" name="act" value="2" />
        <input type="hidden" name="vid2" value="{$merchantProperty.to_vid}" />
        <table id="send_validate" class="send_res" cellpadding="1" cellspacing="1">
            <tbody>
                <tr>
                    <td class="ico">
                        <img class="r1" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_1}" title="{#item_title_1}">
                    </td>
                    <td class="nam">
                        {#item_title_1}:
                    </td>
                    <td class="val">
                        <input class="text" type="text" name="r1" id="r1" value="{function="post('r1')"}" readonly="">
                    </td>
                    <td class="max">
                        ({$merchantProperty.capacity})
                    </td>
                </tr>
                <tr>
                    <td class="ico">
                        <img class="r2" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_2}" title="{#item_title_2}">
                    </td>
                    <td class="nam">
                        {#item_title_2}:
                    </td>
                    <td class="val">
                        <input class="text" type="text" name="r2" id="r2" value="{function="post('r2')"}" readonly="">
                    </td>
                    <td class="max">
                        ({$merchantProperty.capacity})
                    </td>
                </tr>
                <tr>
                    <td class="ico">
                        <img class="r3" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_3}" title="{#item_title_3}">
                    </td>
                    <td class="nam">
                        {#item_title_3}:
                    </td>
                    <td class="val">
                        <input class="text" type="text" name="r3" id="r3" value="{function="post('r3')"}" readonly="">
                    </td>
                    <td class="max">
                        ({$merchantProperty.capacity})
                    </td>
                </tr>
                <tr>
                    <td class="ico">
                        <img class="r4" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_4}" title="{#item_title_4}">
                    </td>
                    <td class="nam">
                        {#item_title_4}:
                    </td>
                    <td class="val">
                        <input class="text" type="text" name="r4" id="r4" value="{function="post('r4')"}" readonly="">
                    </td>
                    <td class="max">
                        ({$merchantProperty.capacity})
                    </td>
                </tr>
            </tbody>
        </table>
        <table id="target_validate" class="res_target" cellpadding="1" cellspacing="1">
            <tbody>
                <tr>
                    <td class="vil" colspan="2">
                        {$merchantProperty.vRow.village_name}
                        ( {$merchantProperty.vRow.rel_x} |{$merchantProperty.vRow.rel_y} )
                    </td>
                </tr>
                <tr>
                    <th>
                        {#LANGUI_CUSTBU_MKT_p1_t3} :
                    </th>
                    <td>
                        <a href="profile?uid={$merchantProperty.vRow.player_id}">
                                {$merchantProperty.vRow.player_name}
                        </a>
                    </td>
                </tr>
                <tr>
                    <th>
                        {#text_period_lang} :
                    </th>
                    <td>
                        {$merchantProperty.vRow_time|secondstostring}
                    </td>
                </tr>
                <tr>
                    <th>
                        {#LANGUI_CUSTBU_MKT_p1_t1} :
                    </th>
                    <td>{$merchantProperty.vRow_merchant_num}</td>
                </tr>
                {if="$data.active_plus_account"}
                <tr>
                    <td><select name="gonum" size="0" class="dropdown">
                        <option value="0" selected="selected">1</option>
                        <option value="1">2</option>
                        <option value="2">3</option>
                        <option value="3">4</option>
                        <option value="4">5</option>
                    </td>
                    <td>{#LANGUI_CUSTBU_MKT_p1_t22}</td>
                </tr>
                {/if}
            </tbody>
        </table>
        {/if}
        <div class="clear"></div>
        <p>
            <input type="image" value="ok" name="s1" id="btn_ok" class="dynamic_img" src="{function="add_style('x.gif', ASSETS_DIR)"}" tabindex="8" alt="{#LANGUI_CUSTBU_MKT_p3_t8}">
        </p>
    </form>
</div>
<p></p>
{if="( is_post('r1') && $merchantProperty['showError'] )"}

    {if="( $merchantProperty['vRow'] == NULL )"}
        <p class="error">{#LANGUI_CUSTBU_MKT_p1_t4}</p>
    {elseif="( $merchantProperty['isAgent'] )"}
        <p class="error">{#LANGUI_CUSTBU_MKT_p1_t21}</p>
    {elseif="( !$merchantProperty['available_res'] )"}
        <p class="error">{#LANGUI_CUSTBU_MKT_p1_t5}</p>
    {elseif="( $merchantProperty['ip'] )"}
        <p class="error">{#LANGUI_PAIN_reason}</p>
    {elseif="( $merchantProperty['vRow_merchant_num'] == 0 )"}
        <p class="error">{#LANGUI_CUSTBU_MKT_p1_t6} .</p>
    {elseif="( $merchantProperty['exits_num'] < $merchantProperty['vRow_merchant_num'] )"}
    <p class="error">
        {#LANGUI_CUSTBU_MKT_p1_t7}
        {$merchantProperty.vRow_merchant_num}
        {#LANGUI_CUSTBU_MKT_p1_t8}
    </p>
    {elseif="( $merchantProperty['same_village'] )"}
    <p class="error">{#LANGUI_CUSTBU_MKT_p1_t9}.</p>
    {/if}
{/if}
<p></p>
<p>
     {#LANGUI_CUSTBU_MKT_p1_t10} <b>{$merchantProperty.capacity}</b>
    {#LANGUI_CUSTBU_MKT_p1_t11}.
</p>
<p></p>

    {if="$is_merchant_coming"}
        <h4>{#LANGUI_CUSTBU_MKT_p1_t12}</h4>
        {loop="$merchant_coming"}
            <table class="traders" cellpadding="1" cellspacing="1">
                        <thead>
                            <tr>
                                <td>
                                    {if="( $value['pn'] != '' )"}
                                        <a href="profile?uid={$value.qt.player_id}">{$value.pn}</a>
                                    {else}
                                        <span class="none">[?]</span>
                                    {/if}
                                </td>
                                <td>
                                    {if="( $value['vn'] != '' )"}
                                        <a href="village3?id={$value.qt.village_id}">
                                            <p class="custDir">
                                                {#LANGUI_CUSTBU_MKT_p1_t13}
                                                {$value.vn}
                                            </p>
                                        </a>
                                    {else}
                                        <p class="custDir">
                                            {#LANGUI_CUSTBU_MKT_p1_t13}
                                            <span class="none">[?]</span>
                                        </p>
                                    {/if}
                                </td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>{#LANGUI_CUSTBU_MKT_p1_t14}</th>
                                <td>
                                    <div class="in">
                                        <span id="timer1">{$value.qt.remainingSeconds|secondstostring}</span>
                                        {#LANGUI_CUSTBU_MKT_p1_t15}
                                    </div>
                                </td>
                            </tr>
                            <tr class="res">
                                <th>{#LANGUI_CUSTBU_MKT_p1_t16}</th>
                                <td>
                                    <img class="r1" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_1}" title="{#item_title_1}">
                                    {$value.mResources.0} |
                                    <img class="r2" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_2}" title="{#item_title_2}">
                                    {$value.mResources.1} |
                                    <img class="r3" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_3}" title="{#item_title_3}">
                                    {$value.mResources.2} |
                                    <img class="r4" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_4}" title="{#item_title_4}">
                                    {$value.mResources.3}
                                </td>
                            </tr>
                        </tbody>
            </table>
        {/loop}
    {/if}

    {if="$is_merchant_travel"}
        <h4>{#LANGUI_CUSTBU_MKT_p1_t17}</h4>
        {loop="$merchant_travel"}
            <table class="traders" cellpadding="1" cellspacing="1">
                    <thead>
                        <tr>
                            <td>
                                <a href="profile?uid={$value.qt.player_id}">{$data.name}</a>
                            </td>
                            <td>
                            {if="( $value.vn2 != '' )"}
                                <a href="village3?id={$value.qt.to_village_id}">
                                <p class="custDir">
                                    {if="$value['qt']['merchantBack']"}
                                        {#LANGUI_CUSTBU_MKT_p1_t18}
                                    {else}
                                        {#LANGUI_CUSTBU_MKT_p1_t19}
                                    {/if}
                                    {$value.vn2}
                                </p>
                                </a>
                            {else}
                                    <p class="custDir">
                                        {if="( $value['qt']['merchantBack'] )"}
                                            {#LANGUI_CUSTBU_MKT_p1_t18}
                                        {else}
                                            {#LANGUI_CUSTBU_MKT_p1_t19}
                                        {/if}
                                        <span class="none">[?]</span>
                                    </p>
                            {/if}
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>{#LANGUI_CUSTBU_MKT_p1_t14}</th>
                            <td>
                                <div class="in">
                                    <span id="timer1">{$value.qt.remainingSeconds|secondstostring}</span>
                                    {#LANGUI_CUSTBU_MKT_p1_t15}
                                </div>
                                <div class="at">
                                    {#LANGUI_CUSTBU_MKT_p1_t20}: {$value.merchantNum}
                                </div>
                            </td>
                        </tr>
                        <tr class="res">
                            <th>{#LANGUI_CUSTBU_MKT_p1_t16}</th>
                            <td>
                                {if="( $value['qt']['merchantBack'] )"}
                                    <span class="none">
                                {/if}
                                    <img class="r1" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_1}" title="{#item_title_1}">
                                    {$value.mResources.0} |
                                    <img class="r2" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_2}" title="{#item_title_2}">
                                    {$value.mResources.1} |
                                    <img class="r3" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_3}" title="{#item_title_3}">
                                    {$value.mResources.2} |
                                    <img class="r4" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_4}" title="{#item_title_4}">
                                    {$value.mResources.3}

                                    {if="( $value['qt']['merchantBack'] )"}</span>{/if}
                            </td>
                        </tr>
                    </tbody>
            </table>
        {/loop}
    {/if}

{elseif="( $selectedTabIndex == 1 )"}

    {if="( $merchantProperty['showOfferList'] )"}
        <table id="range" cellpadding="1" cellspacing="1">
                <thead>
                    <tr>
                        <th colspan="5">
                            <a name="h2"></a>
                            {#LANGUI_CUSTBU_MKT_p2_t1}
                        </th>
                    </tr>
                    <tr>
                        <td>{#LANGUI_CUSTBU_MKT_p2_t2}</td>
                        <td>{#LANGUI_CUSTBU_MKT_p2_t3}</td>
                        <td>{#LANGUI_CUSTBU_MKT_p2_t4}</td>
                        <td>{#text_period_lang}</td>
                        <td>{#LANGUI_CUSTBU_MKT_p2_t5}</td>
                    </tr>
             </thead>
            <tbody>
                {loop="$all_offers"}
                    <tr>
                        <td class="val">
                            <img src="{function="add_style('x.gif', ASSETS_DIR)"}" class="r{$value.res1_item_id}" alt="{function="constant('item_title_'.$value['res1_item_id'])"}" title="{function="constant('item_title_'.$value['res1_item_id'])"}" />
                            {$value.res1_value}
                        </td>
                        <td class="val">
                            <img src="{function="add_style('x.gif', ASSETS_DIR)"}" class="r{$value.res2_item_id}" alt="{function="constant('item_title_'.$value['res2_item_id'] )"}" title="{function="constant('item_title_'.$value['res2_item_id'] )"}" >
                            {$value.res2_value}
                        </td>
                        <td class="pla">
                            <a href="village3?id={$value.value.village_id}">{$value.value.player_name}</a>
                        </td>
                        <td class="dur">
                            {$value.value.timeInSeconds|secondstostring}
                        </td>
                        <td class="act none">
                            {$value.acceptResultString}
                        </td>
                    </tr>
                {/loop}
                {if="$_c == 0"}
                    <tr>
                        <td colspan="5" class="none">{#LANGUI_CUSTBU_MKT_p2_t9}</td>
                    </tr>
                {/if}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="5" class="none">
                        {$getPreviousLink} {$getNextLink}
                    </td>
                </tr>
            </tfoot>
        </table>
    {else}
        <table id="summary" cellpadding="1" cellspacing="1">
            <thead>
                <tr>
                    <th colspan="2">{#LANGUI_CUSTBU_MKT_p2_t10}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2" class="desc">
                        {#LANGUI_CUSTBU_MKT_p2_t11}
                        <a href="profile?uid={$merchantProperty.offerProperty.player_id}">
                                {$merchantProperty.offerProperty.player_name}
                        </a>
                    </td>
                </tr>
                <tr>
                    <td class="val">
                        <img class="r{$merchantProperty.offerProperty.res1_item_id}" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{function="constant('item_title_'.$merchantProperty['offerProperty']['res1_item_id'])"}" title="{function="constant('item_title_'.$merchantProperty['offerProperty']['res1_item_id'])"}" >
                        {$merchantProperty.offerProperty.res1_value}
                    </td>
                    <td class="text">{#LANGUI_CUSTBU_MKT_p2_t12}</td>
                </tr>
                <tr>
                    <td class="val">
                        <img  class="r{$merchantProperty.offerProperty.res2_item_id}" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{function="constant('item_title_'.$merchantProperty['offerProperty']['res2_item_id'])"}" title="{function="constant('item_title_'.$merchantProperty['offerProperty']['res2_item_id'])"}">
                        {$merchantProperty.offerProperty.res2_value}
                    </td>
                    <td class="text">
                        {#LANGUI_CUSTBU_MKT_p2_t13} .
                    </td>
                </tr>
            </tbody>
        </table>
        <br />
        <br />
    {/if}

{elseif="( $selectedTabIndex == 2 )"}
    <div id="contract">
    <form method="post" name="snd" action="build?id={$buildingIndex}&t={$selectedTabIndex}" class="sell_resources" >
        <table id="sell" cellpadding="1" cellspacing="1">
            <tbody>
                <tr>
                    <th>{#LANGUI_CUSTBU_MKT_p3_t1}</th>
                    <td class="val">
                        <input class="text" tabindex="1" name="m1" value="" maxlength="6"></td>
                    <td class="res">
                        <select name="rid1" tabindex="2" class="dropdown">
                            <option value="1" selected="selected">{#item_title_1}</option>
                            <option value="2">{#item_title_2}</option>
                            <option value="3">{#item_title_3}</option>
                            <option value="4">{#item_title_4}</option>
                        </select>
                    </td>
                    <td class="tra">
                        <input class="check" type="checkbox" tabindex="5" name="d1" value="1">
                        {#LANGUI_CUSTBU_MKT_p3_t2} :
                        <input class="text" tabindex="6" name="d2" value="2" maxlength="2">{#time_hour_lang}</td>
                </tr>
                <tr>
                    <th>{#LANGUI_CUSTBU_MKT_p3_t3}</th>
                    <td class="val">
                        <input class="text" tabindex="3" name="m2" value="" maxlength="6"></td>
                    <td class="res">
                        <select name="rid2" tabindex="4" class="dropdown">
                            <option value="1">{#item_title_1}</option>
                            <option value="2" selected="selected">{#item_title_2}</option>
                            <option value="3">{#item_title_3}</option>
                            <option value="4">{#item_title_4}</option>
                        </select>
                    </td>
                    <td class="al">
                        <input class="check" type="checkbox" tabindex="7" name="ally" value="1">{#LANGUI_CUSTBU_MKT_p3_t4}</td>
                </tr>
            </tbody>
        </table>
        <p>
            {#LANGUI_CUSTBU_MKT_p1_t1} : {$merchantProperty.exits_num} / {$merchantProperty.total_num}
        </p>
        {if="( $merchantProperty['showError'] )"}
        <p class="error2">
            {if="( $merchantProperty['showError3'] )"}
                {#LANGUI_CUSTBU_MKT_p3_t5}
            {elseif="( $merchantProperty['showError2'] || intval( $_POST['rid1'] ) == intval( $_POST['rid2'] ) )"}
                {#LANGUI_CUSTBU_MKT_p3_t6}
            {elseif="( !$merchantProperty['available_res'] )"}
                {#LANGUI_CUSTBU_MKT_p2_t6}
            {elseif="( $merchantProperty['vRow_merchant_num'] == 0 )"}
                {#LANGUI_CUSTBU_MKT_p3_t7}
            {elseif="( $merchantProperty['exits_num'] < $merchantProperty['vRow_merchant_num'] )"}
                {#LANGUI_CUSTBU_MKT_p2_t7}
            {/if}
            </p>
        {/if}
        <p>
            <input type="image" tabindex="8" value="ok" name="s1" id="btn_ok" class="dynamic_img" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#LANGUI_CUSTBU_MKT_p3_t8}">
        </p>
    </form>
    </div>
    {if="( 0 < $data['offer_merchants_count'] )"}
    <table id="sell_overview" cellpadding="1" cellspacing="1">
        <thead>
            <tr>
                <th colspan="6">{#LANGUI_CUSTBU_MKT_p3_t9}</th>
            </tr>
            <tr>
                <td></td>
                <td>{#LANGUI_CUSTBU_MKT_p3_t1}</td>
                <td>{#LANGUI_CUSTBU_MKT_p3_t3}</td>
                <td>{#LANGUI_CUSTBU_MKT_p1_t1}</td>
                <td>{#LANGUI_CUSTBU_MKT_p3_t10}</td>
                <td>{#text_period_lang}</td>
            </tr>
        </thead>
        <tbody>
            {loop="$merchant_offers"}
            <tr>
                <td class="abo">
                    <a href="build?id={$buildingIndex}&t={$selectedTabIndex}&d={$value.merchant_offer.id}">
                        <img class="del" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#LANGUI_CUSTBU_MKT_p3_t11}" title="{#LANGUI_CUSTBU_MKT_p3_t11}">
                    </a>
                </td>
                <td class="val">
                    <img src="{function="add_style('x.gif', ASSETS_DIR)"}" class="r{$value.res1_item_id}" alt="{function="constant('item_title_'.$value['res1_item_id'] )}"}" title="{function="constant('item_title_'.$value['res1_item_id'] )}"}">
                    {$value.res1_value}
                </td>
                <td class="val">
                    <img src="{function="add_style('x.gif', ASSETS_DIR)"}" class="r{$value.res2_item_id}" alt="{function="constant('item_title_'.$value['res2_item_id'] )}"}" title="{function="constant('item_title_'.$value['res2_item_id'] )}"}">
                    {$value.res2_value}
                </td>
                <td class="tra">
                    {$value.merchant_offer.merchants_num}
                </td>
                <td class="al">
                    {if="$value['merchant_offer']['alliance_only']"}{#LANGUI_CUSTBU_MKT_p3_t13}{else}{#LANGUI_CUSTBU_MKT_p3_t12}{/if}
                </td>
                <td class="dur">
                    {if="0 < $value['merchant_offer']['max_time']"}({$value.merchant_offer.max_time} {#LANGUI_CUSTBU_MKT_p1_t15}){else}-{/if}
                </td>
            </tr>
            {/loop}
        </tbody>
    </table>
    {/if}

{elseif="( $selectedTabIndex == 3 )"}
    <script language="JavaScript">
        var overall;
        function calculateRes()
        {
            resObj=document.getElementsByName("m2");
            overall=0;
            for (i=0; i<resObj.length; i++) {
                var tmp="";
                for (j=0; j<resObj[i].value.length; j++)
                    if ((resObj[i].value.charAt(j)>="0") && (resObj[i].value.charAt(j)<="9")) tmp=tmp+resObj[i].value.charAt(j);
                resObj[i].value=tmp;
                if (tmp=="") tmp="0";
                newRes=Math.round(parseInt(tmp)*summe/100);
                if (((i<3) && (newRes<=max123)) || ((i==3) && (newRes<=max4)))
                    newHTML=newRes;
                else
                    newHTML="<span class='corr'>"+newRes+"</span>";
                document.getElementById("new"+i).innerHTML=newHTML;
                overall+=parseInt(tmp);
            }
            document.getElementById("overall").innerHTML=overall+"%";
        }

        function normalize()
        {
            calculateRes();
            resObj=document.getElementsByName("m2");
            for (i=0; i<resObj.length; i++) {
                tmp=parseInt(resObj[i].value);
                tmp=tmp*(100/overall);
                resObj[i].value=Math.round(tmp);
            }
            calculateRes();
        }

        function calculateRest()
        {
            resObj=document.getElementsByName("m2[]");
            overall=0;
            for (i=0; i<resObj.length; i++) {
                var tmp="";
                for (j=0; j<resObj[i].value.length; j++)
                    if ((resObj[i].value.charAt(j)>="0") && (resObj[i].value.charAt(j)<="9")) tmp=tmp+resObj[i].value.charAt(j);
                if (tmp=="") {
                    tmp="0";
                    newRes=0;
                    resObj[i].value="";
                } else {
                    newRes=parseInt(tmp);
                    if ((i<3) && (newRes>max123)) newRes=max123;
                    if ((i==3) && (newRes>max4)) newRes=max4;
                    resObj[i].value=newRes;
                }
                dif=newRes-parseInt(document.getElementById("org"+i).innerHTML);
                newHTML=dif;
                if (dif>0) newHTML="+"+dif;
                document.getElementById("diff"+i).innerHTML=newHTML;
                overall+=newRes;
            }
            document.getElementById("newsum").innerHTML=overall;
            rest=parseInt(document.getElementById("org4").innerHTML)-overall;
            document.getElementById("remain").innerHTML=rest;
            testSum();
        }

        function fillup(nr) {
            resObj=document.getElementsByName("m2[]");
            if (nr<3) {
                resObj[nr].value=max123;
            } else {
                resObj[nr].value=max4;
            }
            calculateRest();
        }

        function portionOut() {
            restRes=parseInt(document.getElementById("remain").innerHTML);
            rest=restRes;
            resObj=document.getElementsByName("m2[]");
            nullCount=0;
            notNullCount=0;
            // Z?hlen
            for (j=0; j<resObj.length; j++) {
                if ((restRes>0) && (resObj[j].value=="")) nullCount++;
                if ((restRes<0) && (resObj[j].value!="")) notNullCount++;
            }
            // Verteilen
            nullCount2=0;
            if (restRes>0) {
                // In allen Feldern schon Zahlen?
                if (nullCount==0) {
                    for (i=0; i<resObj.length; i++) {
                        free=max123-parseInt(resObj[i].value);
                        resObj[i].value=(parseInt(resObj[i].value)+Math.round(rest/(4-i)));
                        rest=rest-Math.min(free,Math.round(rest/(4-i)));
                        if ((i<3) && (parseInt(resObj[i].value)<max123)) nullCount2++;
                    }
                } else {
                    for (i=0; i<resObj.length; i++) {
                        if (resObj[i].value=="") {
                            resObj[i].value=Math.round(rest/nullCount);
                            rest=rest-Math.round(rest/nullCount);
                            nullCount--;
                        }
                        if ((i<3) && (parseInt(resObj[i].value)<max123)) nullCount2++;
                    }
                }
            } else {
                for (j=0; j<resObj.length; j++) {
                    if (parseInt(resObj[j].value)>0) {
                        resObj[j].value=(parseInt(resObj[j].value)+Math.round(rest/notNullCount));
                        rest=rest-Math.round(rest/notNullCount);
                        notNullCount--;
                    }
                }
            }
            calculateRest();
            // Noch irgendein Rest?
            if (rest>0) {
                if (max123>max4) {
                    for (j=0; j<3; j++) {
                        if (parseInt(resObj[j].value)<max123) {
                            resObj[j].value=(parseInt(resObj[j].value)+Math.round(rest/nullCount2));
                            rest=rest-Math.round(rest/nullCount2);
                            nullCount2--;
                        }
                    }
                } else {
                    resObj[3].value=(parseInt(resObj[3].value)+rest);
                }
            }
            calculateRest();
        }

        function testSum() {
            if (document.getElementById("remain").innerHTML!=0) {
                document.getElementById("submitText").innerHTML="<a href='javascript:portionOut();'>{#LANGUI_CUSTBU_MKT_p4_t1}</a>";
                document.getElementById("submitText").style.display="block";
                document.getElementById("submitButton").style.display="none";
            } else {
                document.getElementById("submitText").innerHTML="";
                document.getElementById("submitText").style.display="none";
                document.getElementById("submitButton").style.display="block";
            }
        }
    </script>
    <script language="JavaScript">
        var summe = {$resources[1]['current_value'] + $resources[2]['current_value'] + $resources[3]['current_value'] + $resources[4]['current_value']}
        var max123 = {$resources.1.store_max_limit};
        var max4 = {$resources.4.store_max_limit};
    </script>

    <form method="post" id="_fm1" name="snd" action="build?id={$buildingIndex}&t={$selectedTabIndex}{if="(isset($_GET['rid']))"}&rid={function="intval($_GET['rid'])"}{/if}">
        <table id="npc" cellpadding="1" cellspacing="1">
            <thead>
                <tr>
                    <th colspan="5">{#LANGUI_CUSTBU_MKT_p4}</th>
                </tr>
                <tr>
                    <td class="all">
                        <a href="javascript:fillup(0);">
                            <img class="r1" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_1}" title="{#item_title_1}">
                        </a>
                        <span id="org0">{$resources.1.current_value}</span>
                    </td>
                    <td class="all">
                        <a href="javascript:fillup(1);">
                            <img class="r2" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_2}" title="{#item_title_2}">
                        </a>
                        <span id="org1">{$resources.2.current_value}</span>
                    </td>
                    <td class="all">
                        <a href="javascript:fillup(2);">
                            <img class="r3" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_3}" title="{#item_title_3}">
                        </a>
                        <span id="org2">{$resources.3.current_value}</span>
                    </td>
                    <td class="all">
                        <a href="javascript:fillup(3);">
                            <img class="r4" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#item_title_4}" title="{#item_title_4}"></a>
                        <span id="org3">{$resources.4.current_value}</span>
                    </td>
                    <td class="sum">
                        {#LANGUI_CUSTBU_MKT_p4_t2} :
                        <span id="org4">
                            {$resources.1.current_value + $resources.2.current_value + $resources.3.current_value + $resources.4.current_value}
                        </span>
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="sel">
                        <input class="text" onkeyup="calculateRest();" name="m2[]" size="5" maxlength="7" value="{if="isset( $_GET['r1'] )"}{function="intval( $_GET['r1'] )"}{/if}">
                        <input type="hidden" name="m1[]" value="{$resources.1.current_value}">
                    </td>
                    <td class="sel">
                        <input class="text" onkeyup="calculateRest();" name="m2[]" size="5" maxlength="7" value="{if="isset( $_GET['r2'] )"}{function="intval( $_GET['r2'] )"}{/if}">
                        <input type="hidden" name="m1[]" value="{$resources.2.current_value}">
                    </td>
                    <td class="sel">
                        <input class="text" onkeyup="calculateRest();" name="m2[]" size="5" maxlength="7" value="{if="isset( $_GET['r3'] )"}{function="intval( $_GET['r3'] )"}{/if}">
                        <input type="hidden" name="m1[]" value="{$resources.3.current_value}">
                    </td>
                    <td class="sel">
                        <input class="text" onkeyup="calculateRest();" name="m2[]" size="5" maxlength="7" value="{if="isset( $_GET['r4'] )"}{function="intval( $_GET['r4'] )"}{/if}">
                        <input type="hidden" name="m1[]" value="{$resources.4.current_value}">
                    </td>
                    <td class="sum">
                        {#LANGUI_CUSTBU_MKT_p4_t2}:
                        <span id="newsum">0</span>
                    </td>
                </tr>
                <tr>
                    <td class="rem">
                        <span id="diff0">
                            - {$resources.1.current_value}
                        </span>
                    </td>
                    <td class="rem">
                        <span id="diff1">
                            - {$resources.2.current_value}
                        </span>
                    </td>
                    <td class="rem">
                        <span id="diff2">
                            -
                            {$resources.3.current_value}
                        </span>
                    </td>
                    <td class="rem">
                        <span id="diff3">
                            - {$resources.4.current_value}
                        </span>
                    </td>
                    <td class="sum">
                        {#LANGUI_CUSTBU_MKT_p4_t3} :
                        <span id="remain">
                            {$resources.1.current_value + $resources.2.current_value + $resources.3.current_value + $resources.4.current_value}
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
        <p id="submitText" style="display: block; ">
            <a href="javascript:portionOut();">{#LANGUI_CUSTBU_MKT_p4_t1}</a>
        </p>
        {if="( $data['gold_num'] < $gameMetadata['plusTable'][6]['cost'] )"}
            <p id="submitButton" style="display: none; ">
                <a href="plus?t=2">
                    <span class="none">{#LANGUI_CUSTBU_MKT_p4_t4}</span>
                </a>
            </p>
        {else}
            <p id="submitButton" style="display: none; ">
                <a href="#" onclick="_('_fm1').submit();return false;">{#LANGUI_CUSTBU_MKT_p4_t5}</a>
                ( {#LANGUI_CUSTBU_MKT_p4_t6}{$gameMetadata.plusTable.6.cost}{#LANGUI_CUSTBU_MKT_p4_t8})
            </p>
        {/if}
        </form>
        <script>calculateRest();testSum();</script>
        <p>
            {#LANGUI_CUSTBU_MKT_p4_t9} .
        </p>
        {if="( isset( $_GET['rid'] ) )"}
        <p>
            <a href="build?id={$rid}" title="{$btext}">{$btext}</a>
        </p>
        {/if}
        <br/>
        <br/>
{/if}