{if="$page == 'show'"}
<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-table"></i> عرض التقارير</h3>
                <div class="box-tool">
                </div>
            </div>
            <div class="box-content">
                <table class="table table-striped table-hover fill-head">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>اسم المهاجم</th>
                            <th>اسم القرية المهاجمة</th>
                            <th>اسم المدافع</th>
                            <th>اسم القرية المدافعة</th>
                            <th>تاريخ الاضافة</th>
                            <th>حالة التقرير</th>
                            <th style="width: 150px">اوامر</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>test</td>
                            <td>test</td>
                            <td>test</td>
                            <td>test</td>
                            <td>test</td>
                            <td>test</td>
                            <td>test</td>
                            <td>
                                <a class="btn btn-primary btn-small" href="#"><i class="icon-edit"></i> </a>
                                <a class="btn btn-danger btn-small" href="#"><i class="icon-trash"></i> </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{elseif="$page == 'read'"}
<!-- BEGIN Main Content -->
<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-reorder"></i>عرض تقرير "phpman"</h3>
                <div class="box-tool">
                </div>
            </div>
            <div class="box-content">

            </div>
        </div>
    </div>
</div>
<!-- END Main Content -->
{/if}