{if="$page == 'show'"}
 <div class="row-fluid" >
    <div class="span6">
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-th-large"></i>التنقل</h3>
            </div>
            <div class="box-content">
                <p>
                    <a href="support?page=show"><button class="btn">كل التذاكر</button></a>
                    <a href="support?page=show&status=0"><button class="btn btn-primary">الجديدة</button></a>
                    <a href="support?page=show&status=1"><button class="btn btn-info">مجاب عليها</button></a>
                    <a href="support?page=show&status=2"><button class="btn btn-gray">بانتظار الرد</button></a>
                    <a href="support?page=show&status=3"><button class="btn btn-danger">مغلقة</button></a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-table"></i> عرض التذاكر</h3>
                <div class="box-tool">
                </div>
            </div>
            <div class="box-content">
                <table class="table table-striped table-hover fill-head">
                    <thead>
                        <tr>
                            <th>S</th>
                            <th>اللاعب</th>
                            <th>عنوان التذكرة</th>
                            <th>القسم</th>
                            <th>تاريخ التذكرة</th>
                            <th>حالة التذكرة</th>
                            <th>اوامر</th>
                        </tr>
                    </thead>
                    <tbody>
                        {loop="$tickets"}
                        {if="$value.type == 1"}
                          {$cat = 'قسم الشكاوى ضد اللاعبين';}
                        {elseif="$value.type == 2"}
                          {$cat = 'قسم الاستفسارات في اللعبه';}
                        {elseif="$value.type == 3"}
                          {$cat = 'قسم مشاكل الذهب والدفع';}
                        {elseif="$value.type == 4"}
                          {$cat = 'قسم مشاكل اللعبة والاقتراحات';}
                        {/if}

                        {if="$value.status == 0"}
                          {$status = '<span class="btn btn-primary">تذكرة جديدة</a>';}
                        {elseif="$value.status == 1"}
                          {$status = '<span class="btn btn-info">مجاب عليها</a>';}
                        {elseif="$value.status == 2"}
                          {$status = '<span class="btn btn-gray">بانتظار الرد</a>';}
                        {elseif="$value.status == 3"}
                          {$status = '<span class="btn btn-danger">مغلقة</a>';}
                        {/if}
                        <tr>
                            <td>{$value.server_id}</td>
                            <td>{$value.username}</td>
                            <td><a class="" href="support?page=read&id={$value.id}">{$value.title}</a></td>
                            <td>{$cat}</td>
                            <td style="direction: ltr;">{$value.added_time}</td>
                            <td>{$status}</td>
                            <td>
                                <a class="btn btn-danger btn-small" onclick="return confirm('هل انت متاكد من حذف التذكرة ؟');" href="support?page=delete&id={$value.id}"><i class="icon-trash"></i> </a>
                            </td>
                        </tr>
                        {/loop}
                    </tbody>
                </table>
                <div class="pagination">
                    {$pagination}
                </div>
            </div>
        </div>
    </div>
</div>
{elseif="$page == 'read'"}
<div class="row-fluid">
    <div class="span8">
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-file"></i> عرض تذكرة " {$ticket.title} "</h3>
            </div>
            <div class="box-content">
                <ul class="messages">
                    <li>
                        <div style="margin-left:0;">
                            <div>
                                <h5>{$ticket.username}</h5>
                                <span class="time" style="float:left;"><i class="icon-time"></i> {$ticket.added_time}</span>
                            </div>
                            <p>{function="nl2br($ticket.content)"}</p>
                        </div>
                    </li>
                  {loop="$replaies"}
                    <li>
                        <div style="margin-left:0;">
                            <div>
                                <h5>{$value.replaier_name}</h5>
                                {if="$value.is_player == 0"}<label class="label label-info">ادارة</label>{/if}
                                <span class="time" style="float:left;"><i class="icon-time"></i> {$value.added_time}</span>
                            </div>
                            <p>{function="nl2br($value.replay)"}</p>
                             <a class="btn btn-danger btn-small" onclick="return confirm('هل انت متاكد من حذف الرد ؟');" href="support?page=read&id={$ticket.id}&cid={$value.id}"><i class="icon-trash"> حذف </i></a>
                        </div>
                    </li>
                  {/loop}
                </ul>

                <div class="messages-input-form">
                    <form method="POST" action="">
                    <input type="hidden" name="ticketid" value="{$ticket.id}" />
                        <div class="input">
                            <textarea name="replay" class="input-block-level" placeholder="اكتب هنا" rows="4"></textarea>
                        </div>
                        <div class="buttons">
                            <button type="submit" class="btn btn-primary"><i class="icon-share-alt"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="span4">
      <div class="box">
        <div class="box-title">
            <h3><i class="icon-table"></i> اعدادات التذكرة</h3>
            <div class="box-tool">
            </div>
        </div>
        <div class="box-content">
            <form action=""  method="POST"  class="form-horizontal">
            <input type="hidden" name="ticketid" value="{$ticket.id}" />
                <div class="control-group">
                  <div>
                      <div class="span11">
                        <select name="status" >
                              <option {if="$ticket.status == 0"}selected="selected"{/if} value="0">تذكرة جديدة</option>
                              <option {if="$ticket.status == 1"}selected="selected"{/if} value="1">مجاب عليها</option>
                              <option {if="$ticket.status == 2"}selected="selected"{/if} value="2">فى انتظار الرد</option>
                              <option {if="$ticket.status == 3"}selected="selected"{/if} value="3">مغلقة</option>
                        </select>
                      </div>
                  </div>
                </div>

                <div class="control-group">
                  <div>
                      <div class="span11">
                        <select name="type" >
                              <option {if="$ticket.type == 1"}selected="selected"{/if} value="1">قسم الشكاوى ضد اللاعبين</option>
                              <option {if="$ticket.type == 2"}selected="selected"{/if} value="2">قسم الاستفسارات في اللعبه</option>
                              <option {if="$ticket.type == 3"}selected="selected"{/if} value="3">قسم مشاكل الذهب والدفع</option>
                              <option {if="$ticket.type == 4"}selected="selected"{/if} value="4">قسم مشاكل اللعبة والاقتراحات</option>
                        </select>
                      </div>
                  </div>
                </div>

                <div class="form-actions">
                    <input type="submit" class="btn btn-primary" value="تعديل">
                    <button type="button" class="btn">مسح</button>
                </div>

            </form>
        </div>
      </div>
    </div>
</div>
{/if}