{function="load_lang('ui/alliance')"}
{if="!$hasAlliance"}
    <h1>{#LANGUI_ALLIANCE_T1}</h1>
	<p></p>
	<p>{#LANGUI_ALLIANCE_T2}</p>
	<p></p>
{else}
    <h1>{$allianceData.name} - {$allianceData.name2}</h1>
    {if="$fullView"}
	    <div id="textmenu">
		    <a href="alliance"{if="$selectedTabIndex == 0"} class="selected"{/if}>{#LANGUI_ALLIANCE_T3}</a>
        {if="$hasAllianceEditRole"}
         |<a href="alliance?t=1"{if="$selectedTabIndex == 1"} class="selected" {/if}>{#LANGUI_ALLIANCE_T4}</a>
        {/if}
         |<a href="alliance?t=2"{if="$selectedTabIndex == 2"} class="selected" {/if}>{#LANGUI_ALLIANCE_T5}</a>
		 |<a href="alliance?t=3"{if="$selectedTabIndex == 3"} class="selected" {/if}>{#LANGUI_ALLIANCE_T6}</a>
		</div>
    {/if}

    {if="$selectedTabIndex == 0"}
    <script type="text/javascript">
	    function getMouseCoords(e)
		{
		    var coords = {};
			if (!e) var e = window.event;
			if (e.pageX || e.pageY)
			{
			    coords.x = e.pageX;coords.y = e.pageY;
			}
			else if (e.clientX || e.clientY)
			{
			    coords.x = e.clientX + document.body.scrollLeft + document.documentElement.scrollLeft;coords.y = e.clientY + document.body.scrollTop + document.documentElement.scrollTop;
			}
			return coords;
		}
		function med_mouseMoveHandler(e, desc_string) {
            var coords = getMouseCoords(e);
            var layer = _("medal_mouseover");
            layer.style.top = (coords.y + 25) + "px";
            layer.style.left = (coords.x - 20) + "px";
            layer.className = "";
            layer.innerHTML  = desc_string;
        }
		function med_closeDescription()
		{
		    var layer = _("medal_mouseover");
			layer.className = "hide";
		}
		layer = document.createElement("div");
		layer.id = "medal_mouseover";
		layer.className = "hide";
		document.body.appendChild(layer);
	</script>
	<table cellpadding="1" cellspacing="1" id="profile">
	    <thead>
		    <tr>
			    <th colspan="2">{#LANGUI_ALLIANCE_T7}</th>
			</tr>
			<tr>
			    <td>{#LANGUI_ALLIANCE_T8}:</td>
				<td>{#LANGUI_ALLIANCE_T9}</td>
			</tr>
		</thead>
		<tbody>
		    <tr>
			    <td class="empty"></td>
				<td class="empty"></td>
			</tr>
			<tr>
			    <td class="details">
				    <table cellpadding="0" cellspacing="0">
					    <tbody>
						    <tr>
							    <th>{#LANGUI_ALLIANCE_T10}:</th>
								<td>{$allianceData.name}</td>
							</tr>
							<tr>
							    <th>{#LANGUI_ALLIANCE_T11}:</th>
								<td>{$allianceData.name2}</td>
							</tr>
							<tr>
							    <td colspan="2" class="empty"></td>
							</tr>
							<tr>
							    <th>{#LANGUI_ALLIANCE_T12}:</th>
								<td>{$allianceData.rank}</td>
							</tr>
							<tr>
							    <th>{#LANGUI_ALLIANCE_T13}:</th>
								<td>{$allianceData.score}</td>
							</tr>
							<tr>
							    <th>{#LANGUI_ALLIANCE_T14}:</th>
								<td>{$allianceData.player_count}</td>
							</tr>
							<tr>
							    <td colspan="2" class="empty"></td>
							</tr>
						{loop="$roles"}
                            <tr>
			                    <th>{$value.role}</th>
				                <td>
				                    <a href="profile?uid={$value.id}">{$value.name}</a>
				                </td>
			                </tr>
                        {/loop}
						    <tr>
							    <td colspan="2" class="empty"></td>
							</tr>
						    <tr>
							    <td class="desc2" colspan="2">{$getAllianceDescription2}</td>
							</tr>
						</tbody>
					</table>
				</td>
				<td class="desc1">{$getAllianceDescription1}</td>
			</tr>
		</tbody>
	</table>
	<script type="text/javascript">
	    function confirmDel ()
		{
		    return confirm ("{#LANGUI_ALLIANCE_T15}");
		}
		function showAllianceRole(uid)
		{
		    p = document.getElementById("ce");
			if (p!=null)
			{
			    p.innerHTML = '<div id="_pwin" class="popup3"><div id="drag" onmousedown="dragStart(event, \'_pwin\')"></div><a href="#" onClick="hideManual(); return false;"><img src="{function="add_style('x.gif', ASSETS_DIR)"}" border="1" class="popup4" alt="Move"></a><iframe frameborder="0" id="Frame" src="alliancerole?uid='+uid+'" width="412" height="440" border="0"></iframe></div>';
			}
			return false;
		}
	</script>
	<table cellpadding="1" cellspacing="1" id="member">
	    <thead>
		    <tr>
			    <th>&nbsp;</th>
				<th>{#LANGUI_ALLIANCE_T16}</th>
				<th>{#LANGUI_ALLIANCE_T17}</th>
				<th>{#LANGUI_ALLIANCE_T18}</th>
            {if="$fullView"}
                <th>&nbsp;</th>
                {if="$RemovePlayerRole"}
                <th>&nbsp;</th>
                {/if}
                {if="$hasAllianceSetRoles"}
                <th>&nbsp;</th>
                {/if}
            {/if}
			</tr>
		</thead>
		<tbody>
        {loop="$allianceData.players"}
            <tr>
			    <td class="ra">{$value.c}.</td>
			    <td class="pla">
				    <a href="profile?uid={$value.id}">{$value.name}</a>
				</td>
				<td class="hab">{$value.total_people_count}</td>
				<td class="vil">{$value.villages_count}</td>
            {if="$fullView"}
                <td class="on">{$value.lastLoginFromHours}</td>
                {if="$RemovePlayerRole"}
                <td class="on">
                    {if="$value.id != $playerId"}
                    <a onclick="return confirmDel();" href="alliance?d={$value.id}">
					    <img class="del" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#LANGUI_ALLIANCE_T19}" title="{#LANGUI_ALLIANCE_T19}">
					</a>
                    {/if}</td>
                {/if}
                {if="$hasAllianceSetRoles"}
                <td class="on">
				    <a onclick="return showAllianceRole({$value.id});" href="#">
				        <img class="def_c" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#LANGUI_ALLIANCE_T20}" title="{#LANGUI_ALLIANCE_T20}">
					</a>
				</td>
                {/if}

            {/if}
            </tr>
        {/loop}
		</tbody>
	</table>
{elseif="$selectedTabIndex == 1"}
    <form action="alliance?t={$selectedTabIndex}" method="post">
	    <table cellpadding="1" cellspacing="1" id="edit" class="vip">
		    <thead>
			    <tr>
				    <th colspan="3">{#LANGUI_ALLIANCE_T7}</th>
				</tr>
				<tr>
				    <td colspan="2">{#LANGUI_ALLIANCE_T8}:</td>
					<td>{#LANGUI_ALLIANCE_T9}:</td>
				</tr>
			</thead>
			<tbody>
			    <tr>
				    <td colspan="2" class="empty"></td>
					<td class="empty"></td>
				</tr>
				<tr>
				    <th>{#LANGUI_ALLIANCE_T10}:</th>
					<td class="birth">
					    <input tabindex="1" class="text day" type="text" name="aname1" value="{$allianceData.name}" maxlength="8">
					</td>
					<td rowspan="4" class="desc1">
					    <textarea tabindex="7" name="be1">{$allianceData.description1}</textarea>
					</td>
				</tr>
				<tr>
				    <th>{#LANGUI_ALLIANCE_T11}:</th>
					<td class="gend">
					    <input tabindex="1" class="text day" type="text" name="aname2" value="{$allianceData.name2}" maxlength="25">
					</td>
				</tr>
				<tr>
				    <td colspan="2" class="empty"></td>
				</tr>
				<tr>
				    <td colspan="2">
					    <textarea tabindex="8" name="be2" rows="15" cols="33">{$allianceData.description2}</textarea>
					</td>
				</tr>
			</tbody>
		</table>
		<table cellpadding="1" cellspacing="1" id="medals">
		    <thead>
			    <tr>
				    <th colspan="5">{#LANGUI_ALLIANCE_T21}</th>
				</tr>
				<tr>
					<td>{#LANGUI_ALLIANCE_T22}</td>
					<td>{#LANGUI_ALLIANCE_T23}</td>
					<td>{#LANGUI_ALLIANCE_T24}</td>
                    <td>{#profile_medal_txt_points}</td>
					<td>{#LANGUI_ALLIANCE_T25}</td>
				</tr>
			</thead>
			<tbody>
			{loop="$Medals"}
                <tr>
				    <td class="typ">{function="constant('medal_row_'.$value.medalData.textIndex)"}</td>
					<td class="ra">{$value.rank}</td>
					<td class="we">{$value.week}</td>
                    <td class="we">{$value.points}</td>
					<td class="bb">[#{$value.medalData.BBCode + $value.week * 10 + ($value.rank - 1)}]</td>
				</tr>
            {/loop}
            </tbody>
		</table>
		<p class="btn">
		    <input type="image" value="" tabindex="9" name="s1" id="btn_ok" class="dynamic_img" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#text_okdone_lang}">
		</p>
	</form>
{elseif="$selectedTabIndex == 2"}
    <table cellpadding="1" cellspacing="1" id="offs">
	    <thead>
		    <tr>
			    <th colspan="4">{#LANGUI_ALLIANCE_T26}<div id="submenu">
				    <a href="alliance?t=2{if="is_get('ac') && get('ac') == 2"}{else}&ac=2{/if}">
					    <img src="{function="add_style('x.gif', ASSETS_DIR)"}" class="btn_def {if="is_get('ac') && get('ac') == 2"}active{/if}" alt="{#LANGUI_ALLIANCE_T27}" title="{#LANGUI_ALLIANCE_T27}">
					</a>
					<a href="alliance?t=2{if="is_get('ac') && get('ac') == 1"}{else}&ac=1{/if}>
					    <img src="{function="add_style('x.gif', ASSETS_DIR)"}" class="btn_off {if="is_get('ac') && get('ac') == 1"}active{/if}" alt="{#LANGUI_ALLIANCE_T28}" title="{#LANGUI_ALLIANCE_T28}">
					</a>
				</div>
				</th>
			</tr>
			<tr>
			    <td>{#LANGUI_ALLIANCE_T16}</td>
				<td>{#LANGUI_ALLIANCE_T7}</td>
				<td>{#LANGUI_ALLIANCE_T29}</td>
			</tr>
		</thead>
		<tbody>
		{$_c = 0}
        {loop="$Reports"}
		{$_c = $_c + 1}
            <tr>
			    <td class="sub">
				    <img src="{function="add_style('x.gif', ASSETS_DIR)"}" class="iReport iReport{$value._rptResultCss}" alt="{$value.btext}" title="{$value.btext}">
					<div>
					    <a href="report?id={$value.id}">{$value.from_player_name} {$value.getreportactiontext} {$value.to_player_name}</a>
					</div>
				</td>
				<td class="al">
                {if="$value.aData != NULL && 0 < $value.aData['alliance_id']"}
                    <a href="alliance?id={$value.aData['alliance_id']}">{$value.aData['alliance_name']}</a>
                {else}-
                {/if}</td>
				<td class="dat">{$value.mdate}</td>
			</tr>
        {/loop}

        {if="$_c == 0"}
            <tr class="none">
			    <td colspan="4">{#LANGUI_ALLIANCE_T30}</td>
			</tr>
        {/if}
		</tbody>
	</table>
{elseif="$selectedTabIndex == 3"}
    {if="!is_get('a')"}
        <table cellpadding="1" cellspacing="1" id="options" class="small_option">
		    <thead>
			    <tr>
				    <th>{#LANGUI_ALLIANCE_T6}</th>
				</tr>
			</thead>
			<tbody>
            {if="$hasAllianceInviteRoles"}
                <tr>
				    <td class="val">
					    <a href="alliance?t={$selectedTabIndex}&a=1">{#LANGUI_ALLIANCE_T31}</a>
					</td>
				</tr>
            {/if}
            {if="$EditContractRole"}
                <tr>
				    <td class="val">
					    <a href="alliance?t={$selectedTabIndex}&a=2">{#LANGUI_ALLIANCE_T32}</a>
					</td>
				</tr>
            {/if}
                <tr>
				    <td class="val">
					    <a href="alliance?t={$selectedTabIndex}&a=3">{#LANGUI_ALLIANCE_T33}</a>
					</td>
				</tr>
			</tbody>
		</table>
    {else}
        <form action="alliance?t={$selectedTabIndex}&a={function="get('a')"}" method="post">
        {if="get('a') == 3"}
            <table cellpadding="1" cellspacing="1" id="quit" class="small_option">
			    <thead>
				    <tr>
					    <th colspan="2">{#LANGUI_ALLIANCE_T33}</th>
					</tr>
				</thead>
				<tbody>
				    <tr>
					    <td colspan="2" class="info">{#LANGUI_ALLIANCE_T34}</td>
					</tr>
					<tr>
					    <th>{#LANGUI_ALLIANCE_T35}:</th>
						<td>
						    <input class="pass text" type="password" name="pw" maxlength="20">
						</td>
					</tr>
				</tbody>
			</table>
			<p>
			    <input type="image" value="ok" name="s1" id="btn_ok" class="dynamic_img" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#text_okdone_lang}">
			</p>
        {if="$hasErrors"}
            <p class="error">{#LANGUI_ALLIANCE_T36}</p>
        {/if}
        {elseif="get('a') == 2"}
            <table cellpadding="1" cellspacing="1" id="diplomacy" class="dipl">
			    <thead>
				    <tr>
					    <th colspan="2"> {#LANGUI_ALLIANCE_T37}</th>
					</tr>
				</thead>
				<tbody>
				    <tr>
					    <th>{#LANGUI_ALLIANCE_T7}</th>
						<td>
						    <input class="ally text" type="text" name="a_name" maxlength="8">
						</td>
					</tr>
				</tbody>
			</table>
			<table cellpadding="1" cellspacing="1" id="hint" class="infos">
			    <thead>
				    <tr>
					    <th colspan="2">{#LANGUI_ALLIANCE_T38}:</th>
					</tr>
				</thead>
				<tbody>
				    <tr>
					    <td colspan="2">{#LANGUI_ALLIANCE_T39}</td>
					</tr>
				</tbody>
			</table>
			<div id="box">
			    <p>
				    <input type="image" value="ok" name="s1" id="btn_ok" class="dynamic_img" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#text_okdone_lang}">
				</p>
            {if="is_post('a_name') && !$hasErrors"}
                <p class="error">{#LANGUI_ALLIANCE_T40} {function="post('a_name')"}.</p>
            {/if}
		    </div>
			<div class="clear"></div>
			<table cellpadding="1" cellspacing="1" id="own" class="dipl">
			    <thead>
				    <tr>
					    <th colspan="3">{#LANGUI_ALLIANCE_T41}</th>
					</tr>
				</thead>
				<tbody>
                {$_c = 0}
                {loop="$Contracts"}
                    {if="$value.status == 1"}
                    {$_c = $_c + 1}
                    <tr>
					    <td class="abo">
						    <a href="alliance?t={$selectedTabIndex}&a={function="get('a')"}&d={$key}">
						        <img class="del" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#LANGUI_ALLIANCE_T42}" title="{#LANGUI_ALLIANCE_T42}">
							</a>
						</td>
						<td>
						    <a href="alliance?id={$key}">{#LANGUI_ALLIANCE_T43} {$value.name}</a>
						</td>
						<td class="wait">{#LANGUI_ALLIANCE_T44}</td>
					</tr>
                    {/if}
				{/loop}
                {if="$_c == 0"}
                    <tr>
					    <td colspan="3" class="none">{#LANGUI_ALLIANCE_T45}</td>
					</tr>
                {/if}
				</tbody>
			</table>
			<table cellpadding="1" cellspacing="1" id="tip" class="infos">
			    <thead>
				    <tr>
					    <th colspan="2">{#LANGUI_ALLIANCE_T46}:</th>
					</tr>
				</thead>
				<tbody>
				    <tr>
					    <td colspan="2">{#LANGUI_ALLIANCE_T47}<span class="e"> [contracts]</span>&nbsp; {#LANGUI_ALLIANCE_T48}. </td>
					</tr>
				</tbody>
			</table>
			<table cellpadding="1" cellspacing="1" id="foreign" class="dipl">
			    <thead>
				    <tr>
					    <th colspan="3">{#LANGUI_ALLIANCE_T49}</th>
				    </tr>
				</thead>
				<tbody>
                {$_c = 0}
                {loop="$Contracts"}
                    {if="$value.status == 2"}
                    {$_c = $_c + 1}
                    <tr>
					    <td class="abo">
						    <a href="alliance?t={$selectedTabIndex}&a={function="get('a')"}&d={$key}">
					            <img class="del" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#LANGUI_ALLIANCE_T42}" title="{#LANGUI_ALLIANCE_T42}">
							</a>
						</td>
						<td>
						    <a href="alliance?id={$key}">{#LANGUI_ALLIANCE_T43} {$value.name}</a>
						</td>
						<td class="wait">
						    <a href="alliance?t={$selectedTabIndex}&a={function="get('a')"}&c={$key}">{#LANGUI_ALLIANCE_T50}</a>
						</td>
					</tr>
                    {/if}
				{/loop}
                {if="$_c == 0"}
                    <tr>
					    <td colspan="3" class="none">{#LANGUI_ALLIANCE_T45}</td>
					</tr>
                {/if}
				</tbody>
			</table>
			<table cellpadding="1" cellspacing="1" id="existing" class="dipl">
			    <thead>
				    <tr>
					    <th colspan="2">{#LANGUI_ALLIANCE_T51}</th>
					</tr>
				</thead>
				<tbody>
                {$_c = 0}
                {loop="$Contracts"}
                {if="$value.status == 0"}
                    {$_c = $_c + 1}
                    <tr>
					    <td class="abo">
						    <a href="alliance?t={$selectedTabIndex}&a={function="get('a')"}&d={$key}">
							    <img class="del" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#LANGUI_ALLIANCE_T42}" title="{#LANGUI_ALLIANCE_T42}">
							</a>
						</td>
						<td colspan="2">
						    <a href="alliance?id={$key}">{#LANGUI_ALLIANCE_T43} {$value.name}</a>
						</td>
					</tr>
                    {/if}
				{/loop}
                {if="$_c == 0"}
                    <tr>
					    <td colspan="3" class="none">{#LANGUI_ALLIANCE_T45}</td>
					</tr>
                {/if}
				</tbody>
			</table>
        {elseif="get('a') == 1"}
            <table cellpadding="1" cellspacing="1" id="invite" class="small_option">
			    <thead>
				    <tr>
					    <th colspan="2">{#LANGUI_ALLIANCE_T31}</th>
					</tr>
				</thead>
				<tbody>
				    <tr>
					    <th>{#LANGUI_ALLIANCE_T11}:</th>
						<td>
						    <input class="name text" type="text" name="a_name" maxlength="20">
						</td>
					</tr>
				</tbody>
			</table>
			<p>
			    <input type="image" value="ok" name="s1" id="btn_ok" class="dynamic_img" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#text_okdone_lang}">
			</p>
        {if="$invitesResult == 1"}
            <p class="error">{#LANGUI_ALLIANCE_T52} {function="post('a_name')"}</p>
        {elseif="$invitesResult == 2"}
            <p class="error">{#LANGUI_ALLIANCE_T53} {function="post('a_name')"}</p>
        {/if}
            <table cellpadding="1" cellspacing="1" id="invitations" class="small_option">
			    <thead>
				    <tr>
					    <th colspan="2">{#LANGUI_ALLIANCE_T54}:</th>
					</tr>
				</thead>
				<tbody>
                {$_c = 0}
                {loop="$allianceData.players_invites"}
                    {$_c = $_c + 1}
                    <tr>
					    <td class="abo">
						    <a href="alliance?t={$selectedTabIndex}&a={function="get('a')"}&d={$key}">
						        <img class="del" src="{function="add_style('x.gif', ASSETS_DIR)"}" alt="{#LANGUI_ALLIANCE_T42}" title="{#LANGUI_ALLIANCE_T42}">
							</a>
						</td>
						<td>
						    <a href="profile?uid={$key}">{#LANGUI_ALLIANCE_T55} {$value}</a>
						</td>
					</tr>
                {/loop}
                {if="$_c == 0"}
                    <tr>
					    <td colspan="2" class="none">{#LANGUI_ALLIANCE_T45}</td>
					</tr>
                {/if}
				</tbody>
			</table>
        {/if}
        </form>
    {/if}
{/if}
{/if}