{function="load_lang('ui/password')"}
    <h1>
        <img src="{function="add_style('x.gif', ASSETS_DIR)"}" class="passwort" alt="{#LANGUI_PWD_T1}">
    </h1>
    <h5>
	    <img src="{function="add_style('x.gif', ASSETS_DIR)"}" class="img_u22" alt="{#LANGUI_PWD_T2}">
    </h5>
{if="($pageState == 1)"}
    <p>{#LANGUI_PWD_T3}</p>
	<form action="password" method="post">
	    <p>
	        <b>{#LANGUI_PWD_T4}</b>
		    <br>
		    <input type="hidden" name="id" value="{$playerId}">
		    <input class="text" type="text" name="email" maxlength="50">
	    </p>
	    <p>
	        <input type="image" value="ok" name="s1" src="{function="add_style('x.gif', ASSETS_DIR)"}" class="dynamic_img" id="btn_ok" alt="{#text_okdone_lang}">
	    </p>
    </form>
{elseif="($pageState == 2)"}
      {#LANGUI_PWD_T5}
{elseif="($pageState == 3)"}
      {#LANGUI_PWD_T6}
{elseif="($pageState == 4)"}
      {#LANGUI_PWD_T7}
{elseif="($pageState == 5)"}
      {#LANGUI_PWD_T8}
{/if}
