{function="load_lang('ui/privacy')"}
<!--Content-->
<div class="wrapper-contact">
    <img src="{function="add_style('background-land.jpg', ASSETS_DIR.'indx/images/')"}" /></a></li>

</div>

<div class="container-fluid section2 contact-content-container">

    <article class="caption-block">
        <h1 class="caption-heading">{#BIGHEAD}</h1>
        <div class="box-info about-desciption contact-block-2">
            <div class="full-privacy-info">
                <h2>{#MIDDLEHEAD_1}</h2>
                <p>{#TEXT_1}</p>
                <h2>{#MIDDLEHEAD_2}</h2>
                <p>{#TEXT_2}</p>
                <h2>{#MIDDLEHEAD_3}</h2>
                <h4>{#SMALLHEAD_1}</h4>
                <p>{#TEXT_3}</p>
                <h4>{#SMALLHEAD_2}</h4>
                <p>{#TEXT_4}</p>
                <h4>{#SMALLHEAD_3}</h4>
                <p>{#TEXT_5}</p>
                <h4>{#SMALLHEAD_4}</h4>
                <p>{#TEXT_6}</p>
                <h4>{#SMALLHEAD_5}</h4>
                <p>{#TEXT_7}</p>
                <h4>{#SMALLHEAD_6}</h4>
                <p>{#TEXT_8}</p>
                <h2>{#MIDDLEHEAD_4}</h2>
                <h4>{#SMALLHEAD_7}</h4>
                <p>{#TEXT_9}</p>
                <h4>{#SMALLHEAD_8}</h4>
                <p>{#TEXT_10}</p>
                <h4>{#SMALLHEAD_9}</h4>
                <p>{#TEXT_11}</p>
                <h4>{#SMALLHEAD_10}</h4>
                <p>{#TEXT_12}</p>
                <h4>{#SMALLHEAD_11}</h4>
                <p>{#TEXT_13}</p>
                <h2>{#MIDDLEHEAD_5}</h2>
                <p>{#TEXT_14}</p>
                <h2>{#MIDDLEHEAD_6}</h2>
                <p>{#TEXT_15}</p>
                <h2>{#MIDDLEHEAD_7}</h2>
                <p>{#TEXT_16}</p>
                <h2>{#MIDDLEHEAD_8}</h2>
                <p>{#TEXT_17}</p>
                <h2>{#MIDDLEHEAD_9}</h2>
                <p>{#TEXT_18}</p>
                <h2>{#MIDDLEHEAD_10}</h2>
                <p>{#TEXT_19}</p>
            </div>
        </div>


    </article>
</div>